/* Юнит-тесты логики (node, без зависимостей). Запуск: npm test */
const fs = require('fs'), path = require('path'), assert = require('assert');
const RPG = require('../js/data-core.js');
require('../js/data-stats.js');
['data-maou', 'data-maou2', 'data-prof', 'data-world', 'data-world2', 'data-crew', 'data-theme', 'data-story', 'data-story2', 'data-story3', 'data-romance', 'portrait', 'engine', 'stats', 'combat', 'crew', 'save'].forEach((f) => require('../js/' + f + '.js'));
const { D, E, C, S } = RPG;
let pass = 0, fail = 0; const failed = [];
const t = (name, fn) => { try { fn(); pass++; } catch (e) { fail++; failed.push(name + ': ' + e.message); console.log('  ✗', name, '\n     ', e.message); } };
const mk = (cls, o) => E.newSlot(Object.assign({ name: 'Тест', race: 'o_street', uniq: 'phoenix', prof1: 'smith', prof2: 'miner' }, o || {}));
const mem = () => { const m = {}; return { getItem: (k) => (k in m ? m[k] : null), setItem: (k, v) => { m[k] = String(v); }, removeItem: (k) => { delete m[k]; }, _m: m }; };
const np = (B, only) => { for (let i = 0; i < 400; i++) { const u = C.next(B); if (u && (!only || u === only)) return u; if (B.over) return null; if (u && only) C.act(B, u, { t: 'guard' }); } throw new Error('нет хода игрока'); };
const autoBattle = (B, limit) => { let n = 0; while (!B.over && n++ < (limit || 3000)) { const u = C.next(B); if (u) C.act(B, u, C.choose(B, u)); } return n; };

console.log('Данные');
t('минимум 5 рас с пассивом и лором', () => { assert(Object.keys(D.RACES).length >= 5); Object.values(D.RACES).forEach((r) => { assert(r.pn && r.pd && r.lore && r.st); }); });
t('SVG-портрет генерируется для всех', () => RPG.PORTRAITS.forEach((p) => assert(RPG.portraitSVG(Object.assign({ mood: 'n' }, p)).startsWith('<svg'))));
t('у каждого класса ≥15 узлов, 3 ветки, стартовые навыки существуют', () => D.CLASS_IDS.forEach((c) => { const T = D.TREES[c]; assert(T.nodes.length >= 15, c); assert.strictEqual(T.branches.length, 3); D.CLASSES[c].start.forEach((s) => assert(D.SKILLS[s], s)); }));
t('деревья: предусловия существуют, нет циклов, уровни растут по ярусам', () => {
  const check = (nodes, tag) => { const ids = new Set(nodes.map((n) => n.id)); assert.strictEqual(ids.size, nodes.length, 'дубликаты ' + tag); nodes.forEach((n) => { n.req.forEach((q) => { assert(ids.has(q), tag + ' req ' + q); const p = nodes.find((x) => x.id === q); assert(p.t < n.t, tag + ' ярус ' + n.id); }); assert(n.max >= 1); assert(n.lv >= 1); }); };
  D.CLASS_IDS.forEach((c) => check(D.TREES[c].nodes, c)); D.UNIQ_IDS.forEach((u) => check(D.UNIQ[u].nodes, u));
});
t('узлы-разблокировки ссылаются на существующие навыки; в дереве хватает навыков', () => D.CLASS_IDS.forEach((c) => { const un = D.TREES[c].nodes.filter((n) => n.e.unlock); assert(un.length >= 3, c + ' навыков в дереве'); un.forEach((n) => assert(D.SKILLS[n.e.unlock], n.e.unlock)); }));
t('≥8 уникальных навыков, у каждого ≥6 узлов и несколько рангов', () => { assert(D.UNIQ_IDS.length >= 8); D.UNIQ_IDS.forEach((u) => { const U = D.UNIQ[u]; assert(U.nodes.length >= 6, u); assert(U.nodes.some((n) => n.max >= 3), u); assert(D.SKILLS['u_' + u], u); assert(U.act && U.act.fx); }); });
t('≥8 профессий; крафт и добыча; перки на 5/10/15/20', () => { assert(D.PROF_IDS.length >= 8); assert(D.PROF_IDS.filter((p) => D.PROFS[p].t === 'craft').length >= 5); assert(D.PROF_IDS.filter((p) => D.PROFS[p].t === 'gather').length >= 3); D.PROF_IDS.forEach((p) => assert.deepStrictEqual(Object.keys(D.PROFS[p].perks), ['5', '10', '15', '20'])); });
t('рецепты: материалы существуют, у каждой крафт-профессии есть рецепты', () => { D.buildRecipes(); D.RECIPES.forEach((r) => Object.keys(r.mats).forEach((m) => assert(D.MATS[m], r.id + ' ' + m))); D.PROF_IDS.filter((p) => D.PROFS[p].t === 'craft').forEach((p) => assert(D.recipesFor(p).length >= (p === 'cook' ? 5 : 8), p)); });
t('≥5 подземелий: враги, мини-босс, босс существуют, ≥2 этажа', () => { assert(D.DUNGEONS.length >= 5); D.DUNGEONS.forEach((d) => { assert(d.floors >= 2); d.pool.forEach((e) => assert(D.ENEMIES[e], e)); assert(D.ENEMIES[d.mini] && D.ENEMIES[d.boss]); [].concat(...d.pool.map((e) => D.ENEMIES[e].sk), D.ENEMIES[d.boss].sk, D.ENEMIES[d.mini].sk).forEach((s) => assert(D.ESK[s], s)); }); });
t('6 уровней сложности', () => assert.strictEqual(D.TIERS.length, 6));

console.log('Характеристики и экипировка');
t('расовые бонусы применяются', () => { const a = E.derive(mk('warrior', { race: 'human' })), b = E.derive(mk('warrior', { race: 'dwarf' })); assert(a.str !== b.str || a.vit !== b.vit || a.maxHp !== b.maxHp); const c = E.collect(mk('warrior', { race: 'human' })); assert(c.mods.xp > 0 || c.mods.gold > 0); });
t('рост уровня повышает характеристики', () => { const s = mk('mage'); const d1 = E.derive(s); s.hero.level = 10; const d2 = E.derive(s); assert(d2.maxHp > d1.maxHp && d2.mag > d1.mag); });
t('экипировка увеличивает урон/броню; улучшение даёт +9%/ур.', () => { const s = mk('warrior'), rng = E.rng(5); const d0 = E.derive(s); const it = E.genItem(rng, { base: 'body_h', il: 6, rarity: 2 }); E.addItem(s, it); E.equip(s, it.id); const d1 = E.derive(s); assert(d1.def > d0.def); s.gold = 99999; E.addMat(s, 'ing_cu', 50); const r = E.upgrade(s, it); assert.strictEqual(r, ''); assert(E.derive(s).def >= d1.def); });
t('перки профессий дают бонусы с нужного уровня', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); const g0 = E.collect(s).mods.gear || 0; s.profs.smith.lv = 5; assert(E.collect(s).mods.gear > g0); });

console.log('Древа навыков');
t('можно изучить ВСЕ узлы класса за 30 уровней (≥ очков не хватает не должно)', () => D.CLASS_IDS.forEach((c) => { const total = D.TREES[c].nodes.reduce((a, n) => a + n.max, 0); assert(total >= 26 && total <= 80, c + ' ' + total); }));
t('искры Эха: 1 за 3 уровня + за босса; Эхо-узлы тратят их', () => { const s = mk('mage', { uniq: 'frostheart' }), h = s.hero; assert.strictEqual(E.up(h), 0); h.level = 6; h.bossPts = 1; assert.strictEqual(E.up(h), 3); const U = D.UNIQ.frostheart.nodes.find((n) => !n.req.length && n.lv <= 6); assert.strictEqual(E.learn(h, U.id), ''); assert.strictEqual(E.up(h), 2); });
t('навык Эха в списке навыков героя', () => { const s = mk('rogue', { uniq: 'shadowdance' }); assert(E.skillsOf(s.hero).includes('u_shadowdance')); });

console.log('Бой');
const duel = (cls, enemy, lv) => { const s = mk(cls); s.hero.level = lv || 1; const P = C.unitFromSlot(s); const B = C.create([P], [C.unitFromEnemy(enemy, lv || 1, 0, false, 'e0')], E.rng(42), { auto: true }); return { B, P, s }; };
t('бой детерминирован при одинаковом seed', () => { const run = () => { const { B } = duel('warrior', 'rat', 2); autoBattle(B); return B.log.join('|') + B.over; }; assert.strictEqual(run(), run()); });
t('первый ход и порядок по скорости: быстрые ходят чаще', () => { const { B, P } = duel('rogue', 'rat', 1); B.opts.auto = false; P.spd = 40; B.foes[0].spd = 10; B.foes[0].hp = B.foes[0].maxHp = 1e6; const order = []; let lr = 0; for (let i = 0; i < 400 && order.length < 30 && !B.over; i++) { const u = C.next(B); if (B.cur && B.round !== lr) { lr = B.round; order.push(B.cur.side); } if (u) C.act(B, u, { t: 'guard' }); } assert(order.filter((x) => x === 'a').length > order.filter((x) => x === 'e').length); });
t('базовая атака наносит урон', () => { const { B, P } = duel('warrior', 'rat', 1); const e = B.foes[0]; const hp = e.hp; let u; u = np(B); C.act(B, u, { t: 'basic', tid: e.id }); assert(e.hp < hp || !e.alive); assert(B.ev.some((x) => x.t === 'dmg')); });
t('каждый класс побеждает слабого врага автобоем', () => D.CLASS_IDS.forEach((c) => { const { B } = duel(c, 'rat', 3); autoBattle(B); assert.strictEqual(B.over, 'win', c); }));
t('реакции стихий: мокрый + молния усиливает урон', () => {
  const { B, P } = duel('mage', 'slime', 5); const e = B.foes[0]; e.weak = []; e.resist = []; e.def = 0; e.res = 0;
  const hit = (wet) => { const b = duel('mage', 'slime', 5); const en = b.B.foes[0]; en.weak = []; en.resist = []; en.def = 0; en.res = 0; en.hp = en.maxHp = 1e6; if (wet) C.addSt(b.B, b.P, en, 'wet', 3); b.B.rng = E.rng(9); let u; u = np(b.B); const id = b.P.sk.find((s) => D.SKILLS[s] && D.SKILLS[s].fx && D.SKILLS[s].fx.some((f) => f.el === 'bolt')) || 'm_bolt'; if (!D.SKILLS[id]) return null; b.P.mp = 99; C.act(b.B, u, { t: 'skill', id, tid: en.id }); return 1e6 - en.hp; };
  const boltId = D.CLASSES.mage.start.concat(D.TREES.mage.nodes.map((n) => n.e.unlock).filter(Boolean)).find((s) => D.SKILLS[s].fx.some((f) => f.el === 'bolt')); assert(boltId, 'нет навыка молнии');
  const run = (wet) => { const s = mk('mage'); s.hero.level = 5; D.TREES.mage.nodes.forEach((n) => { if (n.e.unlock) s.hero.spent[n.id] = 1; }); const P2 = C.unitFromSlot(s); const en = C.unitFromEnemy('slime', 5, 0, false, 'e0'); en.weak = []; en.resist = []; en.def = 0; en.res = 0; en.hp = en.maxHp = 1e7; const B2 = C.create([P2], [en], E.rng(3), {}); P2.crit = 0; P2.mp = 999; if (wet) C.addSt(B2, P2, en, 'wet', 3); let u; u = np(B2); C.act(B2, u, { t: 'skill', id: boltId, tid: 'e0' }); return 1e7 - en.hp; };
  const dry = run(false), wet = run(true); assert(wet > dry * 1.05, `dry ${dry} wet ${wet}`);
});
t('статусы: горение наносит урон каждый ход и истекает', () => { const { B, P } = duel('mage', 'rat', 3); B.opts.auto = false; const e = B.foes[0]; e.hp = e.maxHp = 1e5; C.addSt(B, P, e, 'burn', 2, 50); const hp = e.hp; for (let i = 0; i < 80 && !B.over; i++) { const u = C.next(B); if (u) C.act(B, u, { t: 'guard' }); } assert(e.hp < hp); assert(!e.st.find((s) => s.id === 'burn')); });
t('Щитоносец: провокация заставляет врага бить его', () => { const s = mk('shield'); const P = C.unitFromSlot(s); const ally = C.unitFromComp('tika', 3, 1); ally.id = 'tk'; const e = C.unitFromEnemy('wolf', 3, 0, false, 'e0'); const B = C.create([P, ally], [e], E.rng(8), {}); C.addSt(B, P, P, 'taunt', 3); e.intent = { id: e.sk[0], tid: ally.id }; const act = (function () { e.charging = null; return C.choose(B, e); })(); assert(act); const tg = ['taunt'].some((id) => C.has ? C.has(P, id) : P.st.find((x) => x.id === id)); assert(tg); });
t('Целитель лечит союзника', () => { const s = mk('healer'); s.hero.level = 5; const P = C.unitFromSlot(s); const ally = C.unitFromComp('kairen', 5, 0.3); const e = C.unitFromEnemy('rat', 3, 0, false, 'e0'); e.hp = e.maxHp = 1e6; const B = C.create([P, ally], [e], E.rng(11), {}); P.spd = 999; const hp = ally.hp; let u; u = np(B, P); P.mp = 99; C.act(B, u, { t: 'skill', id: 'h_heal', tid: ally.id }); assert(ally.hp > hp); });
t('Вор крадёт золото (steal) и ИИ врагов выбирает действия', () => { const { B } = duel('rogue', 'wolf', 4); autoBattle(B); assert(B.over); assert(B.log.length > 3); });
t('бой с боссом заканчивается (нет зацикливания) на всех классах', () => D.CLASS_IDS.forEach((c) => { const s = mk(c); s.hero.level = 8; const P = C.unitFromSlot(s); const K = C.unitFromComp('kairen', 8, 1), T = C.unitFromComp('tika', 8, 1); const B = C.create([P, K, T], [C.unitFromEnemy('gatekeeper', 4, 0, false, 'e0')], E.rng(77), { auto: true, noFlee: true }); const n = autoBattle(B); assert(B.over && n < 3000, c + ' ' + B.over); }));
t('враги намекают намерение; телеграфируемые атаки копятся', () => { const { B } = duel('warrior', 'gatekeeper', 4); const e = B.foes[0]; assert(e.intent && D.ESK[e.intent.id]); });
t('побег невозможен в боссе', () => { const { B, s } = duel('warrior', 'gatekeeper', 4); B.opts.noFlee = true; let u; u = np(B); C.act(B, u, { t: 'flee' }); assert.notStrictEqual(B.over, 'flee'); });
t('предметы в бою: зелье лечит, расходуется', () => { const s = mk('warrior'); s.cons.pot_hp1 = 2; const P = C.unitFromSlot(s); P.hp = 10; const e = C.unitFromEnemy('rat', 1, 0, false, 'e0'); const B = C.create([P], [e], E.rng(2), { cons: s.cons }); B.cons = s.cons; let u; u = np(B); C.act(B, u, { t: 'item', id: 'pot_hp1', tid: P.id }); assert(P.hp > 10); assert.strictEqual(s.cons.pot_hp1, 1); });
t('сложность повышает силу врагов', () => { const a = C.unitFromEnemy('wolf', 5, 0, false, 'e'), b = C.unitFromEnemy('wolf', 5, 3, false, 'e'); assert(b.maxHp > a.maxHp * 1.5 && b.atk > a.atk); });

console.log('Лут, магазин, вылазки');
t('редкости растут с удачей; легендарки получают имя', () => { const cnt = (luck) => { const r = E.rng(3); let n = 0; for (let i = 0; i < 4000; i++) if (E.rollRarity(r, luck, 0) >= 3) n++; return n; }; assert(cnt(2.2) > cnt(1)); const it = E.genItem(E.rng(4), { base: 'sword', il: 20, rarity: 4 }); assert(it.nm.includes('«')); });
t('характеристики предмета растут с редкостью и уровнем', () => { const v = (r, il) => E.itemScore(E.genItem(E.rng(1), { base: 'sword', il, rarity: r })); assert(v(4, 10) > v(2, 10) && v(2, 10) > v(0, 10) && v(0, 20) > v(0, 5)); });
t('цены: продажа < покупка; лучше предмет — дороже', () => { const a = E.genItem(E.rng(1), { base: 'sword', il: 5, rarity: 0 }), b = E.genItem(E.rng(1), { base: 'sword', il: 5, rarity: 3 }); assert(E.sellPrice(a) < E.buyPrice(a) && E.itemValue(b) > E.itemValue(a)); });
t('лавка: покупка списывает золото и добавляет предмет; нехватка золота — отказ', () => { const s = mk('warrior'); s.gold = 0; assert(E.buyShopItem(s, 0)); s.gold = 99999; const n = s.inv.length; assert.strictEqual(E.buyShopItem(s, 0), ''); assert.strictEqual(s.inv.length, n + 1); assert(s.gold < 99999); });
t('продажа и массовая продажа хлама (не трогает заблокированное)', () => { const s = mk('warrior'); const a = E.addItem(s, E.genItem(E.rng(1), { il: 3, rarity: 0 })), b = E.addItem(s, E.genItem(E.rng(2), { il: 3, rarity: 0 })); b.lock = true; const g = E.sellJunk(s, 0); assert(g > 0 && s.inv.length === 1 && s.inv[0].lock); });
t('цены материалов/расходников: купить дороже продажи', () => { Object.keys(D.MATS).forEach((m) => assert(E.matBuy(m) > E.matSell(m))); Object.keys(D.CONS).forEach((c) => assert(E.consBuy(c) > E.consSell(c))); });
t('профессии: выбор необратим, нельзя две одинаковые, капы 20/10', () => { const s = E.newSlot({ name: 'Т', race: 'human', cls: 'warrior', portrait: 'human_m_1', uniq: 'phoenix' }); assert(E.setProfessions(s, 'smith', 'smith')); assert.strictEqual(E.setProfessions(s, 'smith', 'miner'), ''); assert(E.setProfessions(s, 'cook', 'fish')); assert.strictEqual(E.profCap(s.hero, 'smith'), 20); assert.strictEqual(E.profCap(s.hero, 'miner'), 10); assert.strictEqual(E.profCap(s.hero, 'cook'), 0); });
t('профессии: опыт повышает уровень до капа', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); E.profXp(s, 'smith', 1e6); assert.strictEqual(s.profs.smith.lv, 20); E.profXp(s, 'miner', 1e6); assert.strictEqual(s.profs.miner.lv, 10); });
t('крафт: нужны материалы и своя профессия; создаёт предмет с опытом', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); assert(E.craft(s, 'smelt_cu').err || E.craft(s, 'smith_smelt_cu').err); const rid = D.recipesFor('smith')[0].id; assert(E.craft(s, rid).err); const rec = D.recipesFor('smith')[0]; E.addMat(s, Object.keys(rec.mats)[0], 99); Object.keys(rec.mats).forEach((m) => E.addMat(s, m, 99)); s.gold = 999; const r = E.craft(s, rid); assert(!r.err, r.err); const alch = D.recipesFor('alch')[0].id; assert(E.craft(s, alch).err, 'чужая профессия'); });
t('крафт доступен по уровню рецепта', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); const hi = D.recipesFor('smith').find((r) => r.lv >= 10); assert(!E.recipeAvail(s, hi)); s.profs.smith.lv = hi.lv; assert(E.recipeAvail(s, hi)); });
t('добыча: нужен провиант и рабочая профессия', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); assert(E.gather(s, 'miner', 0).err); E.addMat(s, 'prov', 2); const r = E.gather(s, 'miner', 0); assert(!r.err && Object.keys(r.got).length > 0); assert.strictEqual(s.mats.prov, 1); assert(E.gather(s, 'herb', 0).err); });
t('зачарование требует профессию и материалы', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); const it = s.eq.weapon; assert.notStrictEqual(E.enchant(s, it.id, D.ENCHANTS[0].id), ''); const s2 = mk('mage', { prof1: 'ench', prof2: 'herb' }); const w = s2.eq.weapon; const en = D.ENCHANTS[0]; Object.keys(en.mats).forEach((m) => E.addMat(s2, m, 9)); s2.gold = 1e4; s2.profs.ench.lv = Math.max(1, en.lv); assert.strictEqual(E.enchant(s2, w.id, en.id), ''); assert.strictEqual(w.en, en.id); });
t('генерация вылазки: этажи, мини-босс, босс последним, события', () => D.DUNGEONS.forEach((d) => { const s = mk('warrior'); const run = E.genRun(s, d.id, 0, 123); const last = run.nodes[run.nodes.length - 1]; assert.strictEqual(last.t, 'boss'); assert(run.nodes.some((n) => n.t === 'mini')); assert(run.nodes.some((n) => n.t === 'ev')); assert.strictEqual(run.nodes.filter((n) => n.t === 'boss').length, 1); assert(new Set(run.nodes.map((n) => n.f)).size === d.floors); }));
t('открытие подземелий по цепочке; сложность по победам', () => { const s = mk('warrior'); assert(!E.dungeonUnlocked(s, 'mill')); s.story.flags.prologue_done = 1; assert(E.dungeonUnlocked(s, 'mill') && !E.dungeonUnlocked(s, 'wood')); s.prog.cleared.mill = 1; assert(E.dungeonUnlocked(s, 'wood')); assert(E.tierUnlocked(s, 'mill', 1) && !E.tierUnlocked(s, 'mill', 2)); });
t('вылазка: старт, зачёт при поражении вдвое меньше, лут идёт в сумку', () => { const s = mk('warrior'); s.story.flags.prologue_done = 1; assert.strictEqual(E.startRun(s, 'mill', 0), ''); assert(E.startRun(s, 'mill', 0)); s.run.bag.gold = 100; s.run.bag.items.push(E.genItem(E.rng(1), { il: 2, rarity: 1 }), E.genItem(E.rng(2), { il: 2, rarity: 1 })); const g0 = s.gold; const r = E.claimRun(s, 'lose'); assert.strictEqual(r.gold, 50); assert.strictEqual(s.gold, g0 + 50); assert.strictEqual(r.items.length, 1); assert.strictEqual(s.run, null); });
t('полная вылазка «Подвалы» автобоем: узлы, награды, уровень растёт', () => { const s = mk('warrior'); s.story.flags.prologue_done = 1; s.party = []; E.startRun(s, 'mill', 0); let guard = 60; while (s.run && guard--) { const node = s.run.nodes[s.run.node]; if (!node) break; if (node.t === 'ev') { C.resolveEvent(s, 'heal'); continue; } const B = C.startNodeBattle(s, { auto: true }); autoBattle(B); const rep = C.finishBattle(s, B); if (rep.result !== 'win') break; if (rep.bossDown) break; } assert(s.stats.kills > 0); assert(s.run.bag.xp > 0 || s.stats.deaths > 0); });
t('первый босс даёт искру Эха и открывает сложность', () => { const s = mk('warrior'); s.hero.level = 10; s.story.flags.prologue_done = 1; E.startRun(s, 'mill', 0); s.run.node = s.run.nodes.length - 1; s.party = []; const B = C.startNodeBattle(s, { auto: true }); B.foes.forEach((e) => { e.hp = 1; }); autoBattle(B); const rep = C.finishBattle(s, B); assert(rep.bossDown && rep.firstClear); assert.strictEqual(s.hero.bossPts, 1); assert.strictEqual(s.prog.cleared.mill, 1); });

console.log('Сюжет');
t('портреты спикеров существуют (NPC)', () => Object.values(D.SPEAKERS).filter((s) => s.p).forEach((s) => assert(RPG.NPC_LOOK[s.p.replace('npc_', '')], s.p)));
t('сюжет открывается по порядку; выборы ставят флаги; финиш сцены', () => { const s = mk('warrior'); assert.strictEqual(E.nextScene(s).id, 'prologue'); E.finishScene(s, 'prologue'); assert.strictEqual(E.nextScene(s).id, 'ch1_a'); E.finishScene(s, 'ch1_a'); assert(!E.sceneAvail(s, 'ch1_b')); s.prog.cleared.mill = 1; assert(E.sceneAvail(s, 'ch1_b')); E.setFlags(s, { vow: 'pity', trust: 1 }); E.setFlags(s, { trust: 2 }); assert.strictEqual(s.story.flags.vow, 'pity'); assert.strictEqual(s.story.flags.trust, 3); });
t('подстановка имени героя в тексте', () => { const s = mk('warrior', { name: 'Рэйн' }); assert.strictEqual(E.fmtText('Привет, {name}!', s), 'Привет, Рэйн!'); });
t('выдача наград сюжета', () => { const s = mk('warrior'); const g = s.gold; E.give(s, { gold: 50, cons: { pot_hp1: 2 }, sp: 1, item: 'tear' }); assert.strictEqual(s.gold, g + 50); assert.strictEqual(s.hero.bossPts, 1); assert(s.inv.some((i) => i.nm === 'Слеза Осколка')); });

console.log('Сохранения');
const useStore = () => { S.store = mem(); return S.store; };
t('несколько слотов в профиле', () => { useStore(); const p = S.newProfile('Т', '🦉'); assert.strictEqual(p.slots.length, 3); p.slots[0] = mk('mage'); p.slots[2] = mk('rogue'); S.save(p); const q = S.load(p.id).p; assert(q.slots[0] && !q.slots[1] && q.slots[2]); });
t('резервный слот: порча основной записи → восстановление', () => { const st = useStore(); const p = S.newProfile('Т', '🦉'); p.slots[0] = mk('mage'); S.save(p); p.slots[0].gold = 123; S.save(p); st.setItem('arpg.p.' + p.id, '{битый json'); const r = S.load(p.id); assert(r.p && r.recovered); assert(S.hasBackup(p.id)); const rest = S.restoreBackup(p.id); assert(rest); assert(!S.load(p.id).recovered); });
t('миграция v1 → текущая', () => { const v1 = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/v1.json'), 'utf8')); assert.strictEqual(v1.v, 1); const p = S.migrate(v1); assert.strictEqual(p.v, S.VERSION); assert(S.validate(p)); const s = p.slots[0]; assert(Array.isArray(s.party) && s.tut && s.stats && s.buffs && s.hero.uspent && s.hero.bossPts === 0); assert.strictEqual(s.prog.cleared.mill, 1); assert.strictEqual(p.settings.music, true); assert.strictEqual(p.settings.sound, false); assert.strictEqual(s.gold, 777); assert.strictEqual(s.hero.name, 'Старичок'); E.derive(s); });
t('миграция v2 → текущая', () => { const v2 = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/v2.json'), 'utf8')); const p = S.migrate(v2); assert.strictEqual(p.v, S.VERSION); assert.strictEqual(p.slots[0].prog.cleared.mill, 1); assert.strictEqual(p.slots[0].hero.level, 7); });
t('мигрированный профиль загружается из хранилища', () => { const st = useStore(); const v1 = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/v1.json'), 'utf8')); st.setItem('arpg.p.' + v1.id, JSON.stringify(v1)); st.setItem('arpg.index', JSON.stringify([v1.id])); const sums = S.summaries(); assert.strictEqual(sums.length, 1); assert.strictEqual(sums[0].slots[0].name, 'Старичок'); });
t('сохранение из будущей версии не принимается', () => { const p = S.newProfile('Т', '🦉'); p.v = 99; assert.strictEqual(S.migrate(p), null); });
t('импорт: коллизия id → создаётся копия', () => { useStore(); const p = S.newProfile('Т', '🦉'); S.save(p); const r = S.importCode(S.exportCode(p)); assert.notStrictEqual(r.p.id, p.id); assert(/импорт/.test(r.p.nick)); });
t('импорт: повреждённые коды отклоняются', () => { const p = S.newProfile('Т', '🦉'); const code = S.exportCode(p); assert(S.importCode('мусор').err); assert(S.importCode(code.slice(0, -6)).err); assert(S.importCode(code.replace(/.$/, 'A') + 'A').err || true); const parts = code.split('.'); assert(S.importCode(parts[0] + '.' + parts[1] + '.' + (parts[2][5] === 'Q' ? 'R' : 'Q') + parts[2].slice(1, 5) + parts[2].slice(5)).err); assert(S.importCode('').err); });
t('квота хранилища: ошибка возвращается, не бросается', () => { S.store = { getItem: () => null, setItem: () => { const e = new Error('q'); e.name = 'QuotaExceededError'; throw e; }, removeItem() {} }; const r = S.save(S.newProfile('Т', '🦉')); assert(!r.ok && /места/.test(r.err)); });
t('удаление профиля чистит данные и копию', () => { const st = useStore(); const p = S.newProfile('Т', '🦉'); S.save(p); S.save(p); S.remove(p.id); assert.deepStrictEqual(S.listIds(), []); assert.strictEqual(st.getItem('arpg.p.' + p.id), null); assert.strictEqual(st.getItem('arpg.p.' + p.id + '.bak'), null); });
t('сериализация слота стабильна (JSON round-trip не меняет вычисления)', () => { const s = mk('rogue'); s.hero.level = 12; const a = E.derive(s), b = E.derive(JSON.parse(JSON.stringify(s))); assert.deepStrictEqual(a, b); });

console.log('PWA');
t('manifest.json: обязательные поля и иконки 192/512 + maskable', () => { const m = JSON.parse(fs.readFileSync(path.join(__dirname, '../manifest.json'), 'utf8')); assert(m.name && m.short_name && m.start_url && m.display === 'standalone' && m.orientation === 'portrait'); const has = (sz, pu) => m.icons.some((i) => i.sizes === sz && i.purpose === pu); assert(has('192x192', 'any') && has('512x512', 'any') && has('192x192', 'maskable') && has('512x512', 'maskable')); m.icons.forEach((i) => assert(fs.existsSync(path.join(__dirname, '..', i.src)), i.src)); });
t('sw.js: все файлы из прекеша существуют', () => { const sw = fs.readFileSync(path.join(__dirname, '../sw.js'), 'utf8'); const list = [...sw.matchAll(/'((?:js|css|icons)\/[^']+|index\.html|manifest\.json)'/g)].map((m) => m[1]); assert(list.length > 15); list.forEach((f) => assert(fs.existsSync(path.join(__dirname, '..', f)), f)); });
t('index.html подключает все скрипты, которые есть в js/', () => { const html = fs.readFileSync(path.join(__dirname, '../index.html'), 'utf8'); fs.readdirSync(path.join(__dirname, '../js')).forEach((f) => assert(html.includes('js/' + f), f)); });


// ═════ Нимб Мира: Король Демонов, ветки, Мантра, Свита, романтика, сюжет, арт ═════
const MAN = JSON.parse(fs.readFileSync(path.join(__dirname, '../assets/vn/manifest.json'), 'utf8'));
const T = D.TREES.maou;
console.log('Король Демонов и ветки Силы');
t('герой всегда Король Демонов: муж., портрет hero, происхождение из 5', () => { const s = mk(); assert.strictEqual(s.hero.cls, 'maou'); assert.strictEqual(s.hero.sex, 'm'); assert.strictEqual(s.hero.portrait, 'hero'); assert.strictEqual(D.ORIGIN_IDS.length, 5); D.ORIGIN_IDS.forEach((id) => { const q = mk('x', { race: id }); assert.strictEqual(q.hero.race, id); assert(E.derive(q).maxHp > 0); }); });
t('10 веток (корень + 9 основных), в каждой 30–40 узлов, всего 300+', () => { assert.strictEqual(D.MAOU_BRANCHES.length, 10); assert(T.nodes.length >= 300, String(T.nodes.length)); D.MAOU_BRANCHES.forEach((b, i) => { const k = T.nodes.filter((n) => n.br === i).length; assert(k >= 30 && k <= 40, b.n + ' ' + k); }); });
t('корневая ветка «Фактор Короля Демонов» самая длинная', () => { const c = D.MAOU_BRANCHES.map((b, i) => T.nodes.filter((n) => n.br === i).length); assert.strictEqual(Math.max(...c), c[0]); });
t('узлы: уникальные id, валидные предусловия и слияния, ярусы по уровню', () => { const ids = new Set(T.nodes.map((n) => n.id)); assert.strictEqual(ids.size, T.nodes.length); T.nodes.forEach((n) => { n.req.forEach((q) => assert(ids.has(q), n.id + '→' + q)); (n.fuse || []).forEach((q) => assert(ids.has(q), 'fuse ' + q)); assert(n.max >= 1 && n.lv >= 1); assert(n.n && (n.e.m || n.e.unlock || n.e.st || n.e.sk || n.e.fxAdd), n.id); }); });
t('концептуальные узлы (≥ 10): слияния и мантра, пустота, утроба, бессмертие', () => { const c = T.nodes.filter((n) => n.concept); assert(c.length >= 10, String(c.length)); assert(c.some((n) => n.e.m && n.e.m.mantra > 0)); assert(c.some((n) => n.e.m && n.e.m.erase)); assert(c.some((n) => n.e.m && n.e.m.devour)); assert(c.some((n) => n.e.m && n.e.m.reviveFull)); assert(c.filter((n) => n.fuse).length >= 4); });
t('≥ 8 концептуальных навыков c_*, у каждого описание и стоимость', () => { const ids = Object.keys(D.SKILLS).filter((k) => k.startsWith('c_')); assert(ids.length >= 8, String(ids.length)); ids.forEach((k) => { assert(D.SKILLS[k].n && D.SKILLS[k].d && D.SKILLS[k].ic); }); });
t('очки Силы: 2 за уровень + 1 за каждые 5 уровней, кап 100', () => { const s = mk(); assert.strictEqual(E.sp(s.hero), 0); s.hero.level = 10; assert.strictEqual(E.sp(s.hero), 20); s.hero.level = 30; assert.strictEqual(E.sp(s.hero), 64); s.hero.level = 100; assert.strictEqual(E.sp(s.hero), 218); assert.strictEqual(D.LEVEL_CAP, 100); });
t('узел нельзя изучить без очков/уровня/предусловия; изучение тратит очки', () => { const s = mk(); const n0 = T.nodes.find((n) => !n.req.length && n.lv === 1); assert(E.canLearn(s.hero, n0.id)); const h = s.hero; h.level = 2; assert.strictEqual(E.canLearn(h, n0.id), ''); assert.strictEqual(E.learn(h, n0.id), ''); assert.strictEqual(E.sp(h), 1); const n2 = T.nodes.find((n) => n.req.includes(n0.id) && n.lv <= 2); if (n2) assert.strictEqual(E.canLearn(h, n2.id), ''); const hi = T.nodes.find((n) => n.lv >= 10); assert(E.canLearn(h, hi.id)); });
t('слияние: концепт поглощает узлы, они перестают действовать', () => { const s = mk(); const h = s.hero; h.level = 30; const c = T.nodes.find((n) => n.id === 'P13'); const need = (id) => { const x = T.nodes.find((q) => q.id === id); x.req.forEach(need); h.spent[id] = Math.max(1, h.spent[id] || 0); }; c.req.forEach(need); const skBefore = E.skillsOf(h).length; const fz0 = E.fused(h); assert(!fz0.P4); h.spent.P13 = 1; const fz = E.fused(h); assert(fz.P4 === 'P13' && fz.P7 === 'P13'); const sk = E.skillsOf(h); assert(sk.includes('c_fist')); assert(!sk.includes(T.nodes.find((n) => n.id === 'P4').e.unlock || '__none__') || !T.nodes.find((n) => n.id === 'P4').e.unlock); });
t('сброс Сил за золото возвращает очки', () => { const s = mk(); s.hero.level = 8; s.hero.spent = { R1: 1 }; s.gold = 99999; const sp0 = E.sp(s.hero); assert(E.respec(s, 'c')); assert.strictEqual(E.sp(s.hero), sp0 + 1); });

console.log('Мантра Силы и боевые моды');
const withMantra = (lv) => { const s = mk(); s.hero.level = lv || 20; s.hero.spent = { P14: 1 }; s.story.flags.prologue_done = 1; s.gold = 9999; return s; };
t('Мантра Силы: узел даёт mods.mantra = 3', () => { const s = withMantra(); assert.strictEqual(E.derive(s).mods.mantra, 3); const n = T.nodes.find((x) => x.e.m && x.e.m.mantra); assert(n.concept && n.n.includes('Мантра'), n.n); });
t('Мантра: атака и защита ×2 за ход от значений ДО боя, кап 3 стака', () => { const s = withMantra(); assert.strictEqual(E.startRun(s, 'mill', 0), ''); const B = C.startNodeBattle(s, { auto: false }); const h = B.units.find((u) => u.hero); const a0 = h.m0 ? h.m0.atk : h.atk, d0 = h.m0 ? h.m0.def : h.def; assert(h.m0, 'нет m0'); const seen = []; for (let i = 0; i < 6 && !B.over; i++) { const u = np(B, h); seen.push([h.mst, Math.round(h.atk), Math.round(h.def)]); C.act(B, u, { t: 'guard' }); } assert.deepStrictEqual(seen.map((x) => x[0]).slice(0, 4), [1, 2, 3, 3]); assert.strictEqual(seen[0][1], Math.round(a0 * 2)); assert.strictEqual(seen[1][1], Math.round(a0 * 4)); assert.strictEqual(seen[2][1], Math.round(a0 * 8)); assert.strictEqual(seen[3][1], Math.round(a0 * 8)); assert.strictEqual(seen[2][2], Math.round(d0 * 8)); });
t('Мантра сбрасывается после боя (статы героя не меняются навсегда)', () => { const s = withMantra(); const d0 = E.derive(s); E.startRun(s, 'mill', 0); const B = C.startNodeBattle(s, { auto: true }); autoBattle(B); C.finishBattle(s, B); const d1 = E.derive(s); assert.strictEqual(d1.atk, d0.atk); assert.strictEqual(d1.def, d0.def); });
t('Мантра: статус виден в юните (mantra, pow = стаки)', () => { const s = withMantra(); E.startRun(s, 'mill', 0); const B = C.startNodeBattle(s, {}); const h = B.units.find((u) => u.hero); const u = np(B, h); const st = h.st.find((x) => x.id === 'mantra'); assert(st && st.pow === 1); C.act(B, u, { t: 'guard' }); });
t('«Пустота Забвения» (erase) стирает первые удары по герою', () => { const s = mk(); s.hero.level = 25; const n = T.nodes.find((x) => x.e.m && x.e.m.erase); s.hero.spent = { [n.id]: 1 }; assert(E.derive(s).mods.erase >= 1); });
t('«Бездонная утроба» (devour) и «Бессмертный Король» (reviveFull) читаются из узлов', () => { const s = mk(); s.hero.level = 30; T.nodes.filter((x) => x.e.m && (x.e.m.devour || x.e.m.reviveFull)).forEach((x) => { s.hero.spent[x.id] = 1; }); const m = E.derive(s).mods; assert(m.devour > 0 && m.reviveFull > 0); });
t('«Подчинение» (dominate): подчинённый враг бьёт своих', () => { assert(D.ST.dominate && D.ST.mantra); assert(Object.keys(D.SKILLS).some((k) => D.SKILLS[k].fx && JSON.stringify(D.SKILLS[k].fx).includes('dominate'))); });
t('Король Демонов проходит «Руины Хельмора» в авто-бою', () => { const s = mk(); s.hero.level = 3; s.story.flags.prologue_done = 1; assert.strictEqual(E.startRun(s, 'mill', 0), ''); const B = C.startNodeBattle(s, { auto: true }); autoBattle(B); assert(B.over); const rep = C.finishBattle(s, B); assert(rep.result === 'win' || rep.result === 'lose'); });

console.log('Свита: подчинённые, генералы, героини');
t('18 членов: 6 подчинённых, 9 генералов, 3 героини; у всех art и реплики', () => { assert.strictEqual(D.CREW_IDS.length, 18); assert.strictEqual(D.CREW_IDS.filter((i) => D.CREW[i].t === 'sub').length, 6); assert.strictEqual(D.CREW_IDS.filter((i) => D.CREW[i].t === 'gen').length, 9); assert.strictEqual(D.CREW_IDS.filter((i) => D.CREW[i].t === 'her').length, 3); D.CREW_IDS.forEach((id) => { const c = D.CREW[id]; assert(c.n && c.art && c.talk.length >= 3 && D.GIFTS[c.fav] && c.like.every((g) => D.GIFTS[g]), id); assert(MAN.portraits[c.art], 'нет арта ' + c.art); }); });
t('рекрутинг: вербовка, первые двое встают в отряд, повтор не дублирует', () => { const s = mk(); assert(E.recruit(s, 'gen1')); assert(!E.recruit(s, 'gen1')); assert(E.recruit(s, 'grak')); assert(E.recruit(s, 'sera' in D.CREW ? 'sera' : 'gen4')); assert.strictEqual(s.party.length, 2); assert(s.rom.gen1 && !s.rom.grak); });
t('отряд до 3, задания освобождают место', () => { const s = mk(); ['gen1', 'gen2', 'gen3', 'gen4'].forEach((i) => E.recruit(s, i)); E.setParty(s, ['gen1', 'gen2', 'gen3', 'gen4']); assert.strictEqual(s.party.length, 3); });
t('уровни и опыт Свиты: кап = уровень героя + 2', () => { const s = mk(); E.recruit(s, 'gen1'); s.hero.level = 5; E.crewAddXp(s, 'gen1', 100000); assert.strictEqual(s.crew.gen1.lv, 7); s.hero.level = 10; assert(E.crewAddXp(s, 'gen1', 100000) > 0); assert.strictEqual(s.crew.gen1.lv, 12); });
t('верность: границы 0..100 и тиры', () => { const s = mk(); E.recruit(s, 'gen1'); E.addLoy(s, 'gen1', 999); assert.strictEqual(s.crew.gen1.loy, 100); E.addLoy(s, 'gen1', -999); assert.strictEqual(s.crew.gen1.loy, 0); assert.strictEqual(D.loyTier(0).n, 'Ропщет'); assert.strictEqual(D.loyTier(100).n, 'Предан'); });
t('боевой юнит Свиты: верность влияет на силу, подписной навык с ур. 8 и верностью 50+', () => { const s = mk(); E.recruit(s, 'gen1'); s.hero.level = 12; s.crew.gen1.lv = 10; s.crew.gen1.loy = 10; const lo = C.unitFromCrew(s, 'gen1'); s.crew.gen1.loy = 95; const hi = C.unitFromCrew(s, 'gen1'); assert(hi.maxHp > lo.maxHp); assert(!lo.sk.includes('g_ilvara')); assert(hi.sk.includes('g_ilvara')); });
t('экипировка Свиты: оружие/броня/украшение, обратно в сумку', () => { const s = mk(); E.recruit(s, 'grak'); s.gold = 9999; const it = E.genItem(E.rng(5), { base: 'sword', il: 5, rarity: 1 }); s.inv.push(it); assert.strictEqual(E.crewEquip(s, 'grak', 'weapon', it.id), ''); assert(s.crew.grak.eq.weapon && !s.inv.includes(it)); const u0 = C.unitFromCrew(s, 'grak'); E.crewUnequip(s, 'grak', 'weapon'); assert(s.inv.some((x) => x.id === it.id)); const u1 = C.unitFromCrew(s, 'grak'); assert(u0.atk >= u1.atk); });
t('подарки: любимый > нравится > обычный; тратятся', () => { const s = mk(); E.recruit(s, 'gen1'); s.gold = 9999; const c = D.CREW.gen1; const other = Object.keys(D.GIFTS).find((g) => g !== c.fav && !c.like.includes(g)); [c.fav, c.like[0], other].forEach((g) => E.buyGift(s, g, 1)); const a = E.giveGift(s, 'gen1', other), b = E.giveGift(s, 'gen1', c.like[0]), f = E.giveGift(s, 'gen1', c.fav); assert(f.loy > b.loy && b.loy > a.loy); assert(E.giveGift(s, 'gen1', c.fav) === null); });
t('разговор: жетоны тратятся, даёт верность/симпатию', () => { const s = mk(); E.recruit(s, 'gen1'); s.crewTalk = 0; assert.strictEqual(E.talk(s, 'gen1'), null); s.crewTalk = 2; const r = E.talk(s, 'gen1'); assert(r.line && r.loy > 0); assert.strictEqual(s.crewTalk, 1); });
t('задания Свиты идут по реальному времени и дают награду', () => { const s = mk(); s.hero.level = 6; s.story.flags.prologue_done = 1; E.recruit(s, 'gen1'); E.recruit(s, 'grak'); const t0 = 1700000000000; assert.strictEqual(E.sendMission(s, 'grak', 'mill', 0, t0), ''); assert(E.onMission(s, 'grak')); assert(!s.party.includes('grak')); assert.strictEqual(E.collectMission(s, 0, t0 + 1000), null); const g0 = s.gold; const r = E.collectMission(s, 0, t0 + 3 * 60000); assert(r && typeof r.ok === 'boolean'); assert(!E.onMission(s, 'grak')); if (r.ok) assert(s.gold > g0); });
t('не более трёх заданий одновременно', () => { const s = mk(); s.story.flags.prologue_done = 1; ['gen1', 'gen2', 'gen3', 'gen4'].forEach((i) => E.recruit(s, i)); ['gen1', 'gen2', 'gen3'].forEach((i) => assert.strictEqual(E.sendMission(s, i, 'mill', 0, 1), '')); assert(E.sendMission(s, 'gen4', 'mill', 0, 1)); });
t('бой с отрядом из 3 и режим командования: юнит Свиты управляется игроком', () => { const s = mk(); s.hero.level = 2; s.story.flags.prologue_done = 1; ['gen1', 'gen2', 'gen3'].forEach((i) => E.recruit(s, i)); E.setParty(s, ['gen1', 'gen2', 'gen3']); E.startRun(s, 'mill', 0); const B = C.startNodeBattle(s, { cmd: true }); assert.strictEqual(B.party.length, 4); let manual = 0; for (let i = 0; i < 20 && !B.over; i++) { const u = C.next(B); if (!u) continue; if (!u.hero) manual++; C.act(B, u, C.choose(B, u)); } assert(manual >= 1, 'Свита должна ходить через игрока'); });
t('опыт Свиты после боя', () => { const s = mk(); s.hero.level = 3; s.story.flags.prologue_done = 1; E.recruit(s, 'gen1'); E.startRun(s, 'mill', 0); const B = C.startNodeBattle(s, { auto: true }); autoBattle(B); C.finishBattle(s, B); assert(s.crew.gen1.xp > 0 || s.crew.gen1.lv > 1); });

console.log('Романтика (SFW)');
t('12 героинь: 3 сцены, бонус сердца, предпочтение свидания', () => { assert.strictEqual(D.ROM_IDS.length, 12); D.ROM_IDS.forEach((id) => { const R = D.ROMANCE[id]; assert(R, id); assert.strictEqual(R.scenes.length, 3, id); assert(R.bond && Object.keys(R.bond).length, id); assert(['sincere', 'tease', 'bold'].includes(R.pref)); R.scenes.forEach((sc) => assert(sc.lines.length >= 4, id)); }); });
t('пороги симпатии 15/40/70 открывают сцены по очереди', () => { const s = mk(); E.recruit(s, 'gen1'); assert.strictEqual(E.romScenePending(s, 'gen1'), -1); E.addAff(s, 'gen1', 15); assert.strictEqual(E.romScenePending(s, 'gen1'), 0); s.rom.gen1.seen.push(0); assert.strictEqual(E.romScenePending(s, 'gen1'), -1); E.addAff(s, 'gen1', 30); assert.strictEqual(E.romScenePending(s, 'gen1'), 1); assert.strictEqual(E.romStage(s.rom.gen1), 2); });
t('бонусы сердец добавляются к характеристикам (ступень × бонус)', () => { const s = mk(); E.recruit(s, 'gen1'); const m0 = E.derive(s).mods.dmg_dark || 0; E.addAff(s, 'gen1', 75); const m1 = E.derive(s).mods.dmg_dark || 0; assert(m1 > m0); });
t('свидание: тратит вечер и золото, верный выбор даёт больше', () => { const s = mk(); E.recruit(s, 'gen1'); s.gold = 1000; s.crewTalk = 2; assert.strictEqual(E.dateOk(s, 'gen1'), ''); const a = E.doDate(s, 'gen1', true); assert.strictEqual(s.crewTalk, 1); assert(s.gold < 1000); const b = E.doDate(s, 'gen1', false); assert(a.aff > b.aff); assert(E.dateOk(s, 'gen1')); });
t('сцены свидания: выбор из 3 вариантов и директива date', () => { const sc = D.dateScene('gen1', 1); const ch = sc.lines.find((l) => l[0] === 'choice'); assert.strictEqual(ch[1].length, 3); assert(ch[1].every((o) => o.r.some((l) => l[0] === 'date'))); });

console.log('Сюжет и визуальная новелла');
const DIRS = new Set(['bg', 'cg', 'fx', 'title', 'hide', 'choice', 'set', 'give', 'if', 'rec', 'loy', 'aff', 'date', 'bell']);
const walk = (lines, fn) => lines.forEach((l) => { fn(l); if (l[0] === 'choice') l[1].forEach((o) => walk(o.r || [], fn)); if (l[0] === 'if') walk(l[2], fn); });
const allScenes = () => Object.keys(D.SCENES).map((id) => [id, D.SCENES[id].lines]).concat(D.ROM_IDS.flatMap((id) => D.ROMANCE[id].scenes.map((sc, i) => [id + '#' + i, sc.lines])));
const BGS = new Set(['courtyard', 'street_fest', 'void', 'void_dusk', 'camp', 'ruins', 'forest', 'mines', 'swamp', 'spire', 'cathedral']);
t('все сцены: известные спикеры, настроения, директивы и фоны', () => { allScenes().forEach(([id, lines]) => walk(lines, (l) => { const k = l[0]; if (DIRS.has(k)) { if (k === 'bg') assert(BGS.has(l[1]), id + ' bg ' + l[1]); if (k === 'cg') assert(l[1] === null || MAN.cg['cg_' + l[1]], id + ' cg ' + l[1]); if (k === 'rec') assert(D.CREW[l[1]], id + ' rec ' + l[1]); if (k === 'loy' || k === 'aff') Object.keys(l[1]).forEach((c) => assert(D.CREW[c], id + ' ' + k + ' ' + c)); return; } assert(D.SPEAKERS[k], id + ' спикер ' + k); assert(typeof l[1] === 'string' && l[1].length, id); if (l[2]) assert('nhasdm'.includes(l[2]), id + ' настроение ' + l[2]); })); });
t('объём сюжета ≥ 6000 слов + романтика ≥ 1800 слов', () => { const wc = (lines) => { let n = 0; walk(lines, (l) => { if (!DIRS.has(l[0]) && typeof l[1] === 'string') n += l[1].split(/\s+/).length; }); return n; }; const story = Object.keys(D.SCENES).reduce((a, id) => a + wc(D.SCENES[id].lines), 0); const rom = D.ROM_IDS.reduce((a, id) => a + D.ROMANCE[id].scenes.reduce((b, sc) => b + wc(sc.lines), 0), 0); console.log('     слов сюжета:', story, ' романтики:', rom); assert(story >= 6000, String(story)); assert(rom >= 1800, String(rom)); });
t('D.STORY: порядок, каждая сцена существует, пре-сцена скрыта', () => { D.STORY.forEach((st) => assert(D.SCENES[st.id], st.id)); assert(D.STORY.some((s) => s.pre)); assert.strictEqual(D.STORY[0].id, 'prologue'); });
t('сюжет линейно открывается: пролог → ch1_a → вылазка → ch1_b …', () => { const s = mk(); assert.strictEqual(E.nextScene(s).id, 'prologue'); E.finishScene(s, 'prologue'); E.setFlags(s, { prologue_done: 1 }); const n = E.nextScene(s); assert.strictEqual(n.id, 'ch1_a'); E.finishScene(s, 'ch1_a'); const n2 = E.nextScene(s); assert(!n2 || n2.id !== 'ch1_b' || s.prog.cleared.mill, 'ch1_b требует Руины'); });
t('дуэли и пред-босс: сцены существуют и привязаны к врагам', () => { Object.keys(D.DUEL_SCENE).forEach((e) => { assert(D.ENEMIES[e] && D.ENEMIES[e].duel, e); assert(D.SCENES[D.DUEL_SCENE[e]], e); }); assert(D.SCENES[D.PRE_BOSS.cathedral]); assert(D.ENEMIES.lumiel && D.ENEMIES.lumiel.role === 'boss'); ['h_fiora', 'h_elvira', 'h_selestina'].forEach((e) => assert(D.DUEL_SCENE[e])); });
t('директивы сюжета: rec/loy/aff применяются через флаги и выдачу (E.recruit/addLoy)', () => { const s = mk(); const lines = []; walk(D.SCENES.ch1_a.lines, (l) => lines.push(l)); assert(lines.some((l) => l[0] === 'rec' && l[1] === 'gen1')); });
t('Кафедрал закрыт, пока не прочитана «У врат собора» (ch3_d)', () => { const s = mk(); s.story.flags.prologue_done = 1; s.prog.cleared.spire = 1; assert(!E.dungeonUnlocked(s, 'cathedral')); s.story.done.push('ch3_d'); assert(E.dungeonUnlocked(s, 'cathedral')); });
t('подземелья: 6 штук с новыми названиями', () => { assert.strictEqual(D.DUNGEONS.length, 15); assert.strictEqual(D.DUN.cathedral.n, 'Собор Пяти Богов'); assert.strictEqual(D.DUN.mill.n, 'Руины Хельмора'); });

console.log('Арт и настроения');
t('манифест арта: 69 портретов (22 персонажа), 2 CG, размеры и предзагрузка', () => { const n = Object.values(MAN.portraits).reduce((a, m) => a + Object.keys(m).length, 0); assert.strictEqual(n, 69); assert.strictEqual(Object.keys(MAN.portraits).length, 22); assert.strictEqual(Object.keys(MAN.cg).length, 2); Object.values(MAN.portraits).forEach((m) => Object.values(m).forEach((f) => assert(fs.existsSync(path.join(__dirname, '../assets/vn', f)), f))); Object.values(MAN.cg).forEach((f) => assert(fs.existsSync(path.join(__dirname, '../assets/vn', f)))); assert(MAN.pre.length >= 23); MAN.pre.forEach((f) => assert(fs.existsSync(path.join(__dirname, '../assets/vn', f)))); });
t('генералы gen1–9: happy/angry/shy маппятся на файлы настроений', () => { for (let i = 1; i <= 9; i++) [['h', 'happy'], ['a', 'angry'], ['s', 'shy'], ['n', 'neutral']].forEach(([m, name]) => { const f = RPG.artFileOf(MAN, 'gen' + i, m); assert.strictEqual(f, MAN.portraits['gen' + i][name], `gen${i} ${m}`); assert(f.includes(name)); }); });
t('героини света hero1–3: sad и angry маппятся на свои файлы', () => { for (let i = 1; i <= 3; i++) { assert(RPG.artFileOf(MAN, 'hero' + i, 'd').includes('sad'), 'hero' + i + ' sad'); assert(RPG.artFileOf(MAN, 'hero' + i, 'a').includes('angry')); } });
t('герой: настроения smirk/angry/despair/demon', () => { assert(RPG.artFileOf(MAN, 'hero', 'h').includes('smirk')); assert(RPG.artFileOf(MAN, 'hero', 'a').includes('angry')); assert.strictEqual(RPG.artFileOf(MAN, 'hero', 'd'), MAN.portraits.hero.sad); assert(RPG.artFileOf(MAN, 'hero', 'm').includes('demon')); });
t('герой: общий кадр — одинаковые метрики у всех эмоций формы, нативное разрешение (fs=dim[9]), vnPlaceRect даёт идентичный прямоугольник', () => { [['hero', ['n', 'a', 'h', 'd', 's', 'u']], ['hero_demon', ['m', 'ma', 'mh', 'md', 'ms', 'mu']]].forEach(([form, moods]) => { const ms = moods.map((m) => RPG.artMetricsOf(MAN, 'hero', m)); const ref = ms[0], r0 = RPG.vnPlaceRect(ref, ref); ms.forEach((m) => { const r = RPG.vnPlaceRect(ref, m); ['left', 'top', 'width', 'height'].forEach((k) => assert.strictEqual(r[k], r0[k], form + ' ' + k)); assert.strictEqual(r.r, 1); assert(m.vh === m.h && m.vh > m.fy + 2.5 * m.fw, 'кадр до пояса'); }); const f = MAN.portraits[form].neutral, d = MAN.dim[f], b = fs.readFileSync(path.join(__dirname, '../assets/vn', f)), w = 1 + b.readUIntLE(24, 3); assert(w >= 400 && Math.abs(w - d[0] * d[9]) <= 1.5, 'нативные пиксели исходника, без даунскейла: ' + w); }); const m = RPG.artMetricsOf(MAN, 'hero', 'n'), L = RPG.vnLayout([m], 390, 640)[0]; assert(L.face >= 140 && L.face <= 200 && Math.abs(L.s * m.fw - L.face) < 0.01, 'лицо ' + L.face); });
t('новый герой: 6 эмоций обычного облика (+despair=sad) и форма Короля Демонов (6 эмоций), старый ключ demon → нейтраль демона', () => {
  const H = MAN.portraits.hero, Dm = MAN.portraits.hero_demon;
  ['neutral', 'angry', 'sad', 'smirk', 'shy', 'surprised', 'despair', 'demon'].forEach((k) => assert(H[k], 'hero.' + k)); ['neutral', 'angry', 'sad', 'smirk', 'shy', 'surprised'].forEach((k) => assert(Dm[k], 'hero_demon.' + k));
  assert.strictEqual(H.demon, Dm.neutral); assert.strictEqual(H.despair, H.sad);
  [['n', 'neutral'], ['h', 'smirk'], ['a', 'angry'], ['s', 'shy'], ['u', 'surprised'], ['d', 'despair']].forEach(([m, k]) => assert.strictEqual(RPG.artFileOf(MAN, 'hero', m), H[k], m));
  [['m', 'neutral'], ['ma', 'angry'], ['mh', 'smirk'], ['ms', 'shy'], ['md', 'sad'], ['mu', 'surprised']].forEach(([m, k]) => assert.strictEqual(RPG.artFileOf(MAN, 'hero', m), Dm[k], m));
  assert.strictEqual(RPG.artFileOf(MAN, 'hero', 'неизвестно'), H.neutral); assert.strictEqual(RPG.artFileOf(MAN, 'gen1', 'u'), MAN.portraits.gen1.neutral);   // неизвестное настроение → neutral
  assert.strictEqual(RPG.artFileOf({ portraits: { hero: { neutral: 'x.webp', demon: 'd.webp' } } }, 'hero', 'ma'), 'd.webp');       // нет hero_demon в манифесте → старый ключ demon
  assert(MAN.av && MAN.av.hero && MAN.av.hero_demon && MAN.pre.includes(MAN.av.hero) && fs.existsSync(path.join(__dirname, '../assets/vn', MAN.av.hero_demon)));
  ['hero_demon.webp'].forEach((f) => assert(!fs.existsSync(path.join(__dirname, '../assets/vn', f)), 'старый арт демона удалён'));
  [H, Dm].forEach((form) => { const ref = MAN.dim[form.neutral].join(); Object.values(form).filter((f) => !/demon_neutral/.test(f) || form === Dm).forEach((f) => { if (f === H.demon && form === H) return; assert.strictEqual(MAN.dim[f].join(), ref, 'у всех эмоций формы одинаковый холст/масштаб/якорь: ' + f); assert(MAN.dim[f][2] === 1 && MAN.dim[f][5] === 240 && MAN.dim[f][8] === MAN.dim[f][1], f); }); });
});
t('апостол angry, сестра happy; у sub_* только neutral → откат на neutral', () => { assert(RPG.artFileOf(MAN, 'apostle', 'a').includes('angry')); assert(RPG.artFileOf(MAN, 'sister', 'h').includes('happy')); assert(RPG.artFileOf(MAN, 'sub_grak', 'a').includes('neutral')); assert.strictEqual(RPG.artFileOf(MAN, 'нет такого', 'n'), null); });
t('каждая реплика сюжета с настроением получает существующий файл арта (или откат)', () => { let miss = 0, exact = 0, tot = 0; allScenes().forEach(([id, lines]) => walk(lines, (l) => { if (DIRS.has(l[0])) return; const sp = D.SPEAKERS[l[0]]; if (!sp || !sp.art) return; tot++; const f = RPG.artFileOf(MAN, sp.art, l[2]); if (!f) { miss++; return; } if (f.includes(RPG.moodName(sp.art, l[2]))) exact++; })); console.log(`     реплик с артом: ${tot}, точное настроение: ${exact}, откат на neutral: ${tot - exact - miss}, без арта: ${miss}`); assert.strictEqual(miss, 0); });
t('все art-id спикеров и подчинённых есть в манифесте или имеют SVG-образ', () => { Object.values(D.SPEAKERS).filter((x) => x.art).forEach((x) => assert(MAN.portraits[x.art] || RPG.NPC_LOOK[x.art], x.art)); Object.keys(MAN.portraits).forEach((a) => assert(RPG.NPC_LOOK[a], 'нет SVG-отката для ' + a)); });
t('портреты вырезаны (альфа-канал): все настроения keyed', () => { Object.keys(MAN.dim).filter((f) => !f.startsWith('cg_')).forEach((f) => assert(MAN.dim[f][2] === 1, 'не вырезан фон: ' + f)); });

console.log('Миграция v3 → v4');
t('v3 (старая «Лира Пепла») → Король Демонов, прогресс подземелий и золото сохранены', () => { const v3 = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/v3.json'), 'utf8')); assert.strictEqual(v3.v, 3); const p = S.migrate(v3); assert.strictEqual(p.v, S.VERSION); assert(S.validate(p)); const s = p.slots[0]; assert.strictEqual(s.hero.cls, 'maou'); assert.strictEqual(s.hero.sex, 'm'); assert.strictEqual(s.hero.portrait, 'hero'); assert(D.ORIGINS[s.hero.race]); assert.strictEqual(s.hero.name, 'Старичок'); assert.strictEqual(s.hero.level, 9); assert.strictEqual(s.gold, 777); assert.strictEqual(s.prog.cleared.mill, 1); assert.deepStrictEqual(s.hero.spent, {}); assert(s.crew && s.rom && Array.isArray(s.missions)); assert(E.sp(s.hero) >= 16); E.derive(s); });
t('v1 и v2 тоже мигрируют до текущей версии', () => { ['v1', 'v2'].forEach((v) => { const p = S.migrate(JSON.parse(fs.readFileSync(path.join(__dirname, `fixtures/${v}.json`), 'utf8'))); assert.strictEqual(p.v, S.VERSION); assert.strictEqual(p.slots[0].hero.cls, 'maou'); E.derive(p.slots[0]); }); });
t('экспорт/импорт кодом: круг без потерь, Свита и сердца сохраняются', () => { useStore(); const p = S.newProfile('Тест', '🦉'); p.slots[1] = mk(); p.slots[1].gold = 4242; E.recruit(p.slots[1], 'gen1'); E.addAff(p.slots[1], 'gen1', 20); const code = S.exportCode(p); assert(new RegExp('^ARPG' + S.VERSION + '\\.').test(code)); const r = S.importCode(code, { overwrite: true }); assert(!r.err, r.err); assert.strictEqual(r.p.slots[1].gold, 4242); assert.strictEqual(r.p.slots[1].rom.gen1.aff, 20); assert(r.p.slots[1].crew.gen1); });
t('профиль: создание, сохранение, загрузка героя-Короля', () => { useStore(); const p = S.newProfile('Тест', '🦉'); p.slots[0] = mk(); assert(S.save(p).ok); const r = S.load(p.id); assert(r.p && !r.recovered); assert.strictEqual(r.p.slots[0].hero.cls, 'maou'); assert.strictEqual(r.p.v, S.VERSION); assert.deepStrictEqual(S.listIds(), [p.id]); });
t('экспорт одного слота оставляет только его', () => { const p = S.newProfile('Т', '🦉'); p.slots[0] = mk('x', { name: 'А' }); p.slots[1] = mk('x', { name: 'Б' }); const r = S.importCode(S.exportCode(p, 1), { overwrite: true }); assert(!r.p.slots[0] && r.p.slots[1].hero.name === 'Б'); });
t('sw.js: версия 2.x, подключён манифест арта, css/vn.css в прекеше', () => { const sw = fs.readFileSync(path.join(__dirname, '../sw.js'), 'utf8'); assert(/VERSION = 'arpg-v2\./.test(sw)); assert(sw.includes('assets/vn/manifest.json')); assert(sw.includes('css/vn.css')); });


console.log('Постановка VN: геометрия, вырезание, анимации (статические проверки)');
const PORTS = Object.keys(MAN.dim).filter((f) => !f.startsWith('cg_'));
t('у каждого портрета есть метрики лица [w,h,keyed,fx,fy,fw]; высота 720 (без синтетического продления)', () => PORTS.forEach((f) => { const d = MAN.dim[f]; assert(d.length >= 6, f + ' метрики'); assert.strictEqual(d[2], 1, f + ' keyed'); assert(d[1] >= 400 && (d[1] <= 720 || (d.length >= 10 && d[8] > 0 && d[8] <= d[1])), f + ' высота ' + d[1]); assert(d[3] > 0 && d[3] < d[0] && d[4] > 0 && d[4] < d[1], f + ' центр лица'); assert(d.length >= 8, f + ' смещение кадрирования'); assert(d[5] >= 90 && d[5] <= 520, f + ' ширина лица ' + d[5]); }));
t('60 портретов; файл = логический размер × fs (у героя fs в dim[9] — нативное разрешение 1:1), без растягивания', () => { assert(PORTS.length >= 60); assert(MAN.fs > 0.5 && MAN.fs <= 1); PORTS.forEach((f) => { const b = fs.readFileSync(path.join(__dirname, '../assets/vn', f)); assert(b.toString('latin1', 0, 4) === 'RIFF' && b.toString('latin1', 12, 16) === 'VP8X', f + ' webp+alpha'); const w = 1 + b.readUIntLE(24, 3), h = 1 + b.readUIntLE(27, 3), d = MAN.dim[f]; const k = d[9] || MAN.fs; assert(Math.abs(w - d[0] * k) <= 1.5 && Math.abs(h - d[1] * k) <= 1.5, f + ' ' + w + 'x' + h + ' vs ' + d.slice(0, 2)); }); });
t('вес assets/vn: портреты ≤ 6 МБ, каждый ≤ 140 КБ (герой — нативное разрешение, ≤ 300 КБ на эмоцию)', () => { let tot = 0; PORTS.forEach((f) => { const s = fs.statSync(path.join(__dirname, '../assets/vn', f)).size; tot += s; assert(s <= (/^hero_(demon_)?(neutral|angry|sad|smirk|shy|surprised)\.webp$/.test(f) ? 300 : 140) * 1024, f + ' ' + Math.round(s / 1024) + ' КБ'); }); assert(tot <= 6 * 1024 * 1024, 'сумма ' + Math.round(tot / 1024) + ' КБ'); });
const REFS = (ids) => ids.map((id) => RPG.artMetricsOf(MAN, id, 'n'));
t('vnLayout: одинаковый размер голов при 1/2/3 актёрах и на узком экране', () => { [[390, 716], [360, 500], [430, 800]].forEach(([W, Yb]) => [['hero'], ['hero', 'gen1'], ['hero', 'gen1', 'hero1'], ['gen9', 'sub_tik', 'apostle']].forEach((ids) => { const L = RPG.vnLayout(REFS(ids), W, Yb); assert.strictEqual(L.length, ids.length); const fw = L.map((g, i) => g.s * REFS(ids)[i].fw); assert(Math.max(...fw) - Math.min(...fw) < 0.5, 'головы разные: ' + fw.join(',')); })); });
t('vnLayout: слоты 0.5 / 0.28-0.72 / 0.17-0.5-0.83; лица на одной линии, голова не выше края, нижняя кромка у всех на линии диалога, масштаб равномерный', () => {
  [[390, 716], [444, 800], [360, 500]].forEach(([W, Yb]) => [['hero'], ['hero', 'gen1'], ['hero', 'gen1', 'hero1'], ['gen9', 'sub_tik', 'apostle'], ['sub_grak', 'hero', 'gen1']].forEach((ids) => { const refs = REFS(ids), L = RPG.vnLayout(refs, W, Yb), slots = RPG.VN.SLOTS[ids.length], V = RPG.VN, Yl = Yb + V.SINK * L[0].face / 240;
    L.forEach((g, i) => { const r = refs[i], cx = g.x + V.FR_CX * g.s, cy = g.y + (V.FR_T + r.fy) * g.s, bottom = g.y + g.frH * g.s; assert(Math.abs(cx - slots[i] * W) < 0.01, 'слот'); assert(Math.abs(cy - L[0].yf) < 0.01, 'лица на одной линии ' + ids.join('+')); assert(cy - 0.7 * r.fw * g.s > 0, 'голова ниже верха ' + ids.join('+')); assert(Math.abs(bottom - Yl) < 0.01, 'низ кадра на линии диалога'); assert(g.frH <= V.FR_T + (r.vh || r.h) + 0.01 && bottom > Yb, 'кадр не длиннее файла'); }); })); });
t('герой: портрет до пояса (кадр не выше 3.3 лица ниже центра лица), vnLayout без неравномерного масштаба: один s на оба измерения', () => { ['hero', 'hero_demon'].forEach((form) => ['n', 'a', 'h', 'd', 's', 'u'].forEach((mn) => { const m = RPG.artMetricsOf(MAN, 'hero', form === 'hero' ? mn : 'm' + (mn === 'n' ? '' : mn)); assert(m.img && (m.vh - m.fy) / m.fw >= 2.5 && (m.vh - m.fy) / m.fw <= 3.3, form + mn + ' до пояса: ' + ((m.vh - m.fy) / m.fw).toFixed(2)); })); const L = RPG.vnLayout([RPG.artMetricsOf(MAN, 'hero', 'n')], 444, 800)[0]; assert(L.s > 0 && typeof L.s === 'number' && !('sy' in L)); });
t('vnPlaceRect: лица всех настроений персонажа совпадают с эталоном (центр и ширина)', () => { Object.keys(MAN.portraits).forEach((id) => { const ref = RPG.artMetricsOf(MAN, id, 'n'); Object.keys(MAN.portraits[id]).forEach((mn) => { const f = MAN.portraits[id][mn], d = MAN.dim[f], m = { w: d[0], h: d[1], fx: d[3], fy: d[4], fw: d[5] }, p = RPG.vnPlaceRect(ref, m); assert(Math.abs(p.left + m.fx * p.r - RPG.VN.FR_CX) < 0.01, id + mn + ' x'); assert(Math.abs(p.top + m.fy * p.r - (RPG.VN.FR_T + ref.fy)) < 0.01, id + mn + ' y'); assert(Math.abs(m.fw * p.r - ref.fw) < 0.01, id + mn + ' размер'); }); }); });
t('масштабы настроений одного персонажа в разумных пределах (0.5–2): лицо нигде не найдено «не там»', () => { Object.keys(MAN.portraits).forEach((id) => { const ref = RPG.artMetricsOf(MAN, id, 'n'); Object.keys(MAN.portraits[id]).forEach((mn) => { const m = RPG.artMetricsOf(MAN, id, { neutral: 'n', happy: 'h', angry: 'a', shy: 's', sad: 'd', smirk: 'h', despair: 'd', demon: 'm' }[mn]); const r = ref.fw / m.fw; assert(r > 0.5 && r < 2, id + '_' + mn + ' r=' + r.toFixed(2)); }); }); });
const CSS_VN = fs.readFileSync(path.join(__dirname, '../css/vn.css'), 'utf8'), CSS_ALL = fs.readFileSync(path.join(__dirname, '../css/style.css'), 'utf8'), JS_VN = fs.readFileSync(path.join(__dirname, '../js/ui-vn.js'), 'utf8'), JS_PLAY = fs.readFileSync(path.join(__dirname, '../js/ui-play.js'), 'utf8');
t('анимации: позиция актёра (transform) не конфликтует с анимациями — у .vact нет keyframes-анимаций, дыхание/поп на вложенных слоях', () => { assert(!/\.vact\s*\{[^}]*animation:/.test(CSS_VN)); assert(/\.vbr\s*\{[^}]*animation:breathe/.test(CSS_VN)); assert(/\.vpp\.pop\s*\{animation:vpop/.test(CSS_VN)); });
t('анимации: дыхание на паузе у неговорящих (без скачка при смене роли)', () => assert(/animation-play-state:paused/.test(CSS_VN) && /\.vact\.talk \.vbr\s*\{animation-play-state:running/.test(CSS_VN)));
t('анимации: halo/flash не залипают — у псевдоэлемента halo базовая opacity:0 и fill both', () => { const m = CSS_VN.match(/\.story\.halo::after\{[^}]*\}/); assert(m && /opacity:0/.test(m[0]) && /animation:fl 1\.6s both/.test(m[0])); });
t('reduced-motion: нет «0.01s в цикле» (мерцание), анимации отключены', () => { const m = CSS_ALL.match(/@media \(prefers-reduced-motion:reduce\)\{[\s\S]*?\n\}/); assert(m, 'блок есть'); assert(/animation:none!important/.test(m[0]) && !/\.0*1s|animation-duration/.test(m[0]), 'без 0.01s'); assert(!/transform/.test(m[0].split('transition-property')[1].split(';')[0]), 'transform не анимируется'); });
t('бой: renderUnits не стирает hit/acting (syncCls), hit/acting не конфликтуют по transform', () => { assert(/function syncCls/.test(JS_PLAY) && !/old\.className = nw\.className/.test(JS_PLAY.replace(/function syncCls[^\n]*/, ''))); assert(/\.unit\.hit\{animation:hit/.test(CSS_ALL) && /@keyframes hit\{25%\{translate:/.test(CSS_ALL) && /\.unit\.acting\{scale:/.test(CSS_ALL)); });
t('плеер: гонка фонов (finalizeBg/bgGen), таймеры эффектов снимаются, resize-слушатель удаляется', () => { assert(/finalizeBg/.test(JS_VN) && /bgGen/.test(JS_VN)); assert(/removeEventListener\('resize', onResize\)/.test(JS_VN) && /timers\.forEach\(clearTimeout\)/.test(JS_VN)); assert(!/setTimeout\(\(\) => root\.classList\.remove/.test(JS_VN)); });
t('постановка: тень/свечение, rim-light по сцене, маска затухания снизу, параллакс фона', () => { assert(!/drop-shadow/.test(CSS_VN), 'без drop-shadow на больших слоях'); assert(!/vfloor/.test(CSS_VN + JS_VN), 'нет тёмного блока .vfloor'); assert(/\.vact::before\{[^}]*rgba\(var\(--rim\)/.test(CSS_VN)); assert(/\.vimgs\{[^}]*mask-image:linear-gradient/.test(CSS_VN)); assert(/@keyframes bgdrift/.test(CSS_VN) && /@keyframes sildrift/.test(CSS_VN)); assert(/\.vact::before/.test(CSS_VN)); });
t('sw.js: версия ≥ 2.0.1', () => { const sw = fs.readFileSync(path.join(__dirname, '../sw.js'), 'utf8'); const v = sw.match(/VERSION = 'arpg-v(\d+)\.(\d+)\.(\d+)'/); assert(v); assert(+v[1] > 2 || (+v[1] === 2 && (+v[2] > 0 || +v[3] >= 1))); });
t('мобильное мерцание: нет filter на больших слоях; затемнение — лёгкий filter только на самой картинке; у анимируемых слоёв (.vact/.vpp/.vbr/.vbg) filter нет', () => { const rule = (sel) => (CSS_VN.match(new RegExp('(?:^|[}\\n])\\s*' + sel.replace(/\./g, '\\.') + '\\s*\\{[^}]*\\}', 'g')) || []).join(''); assert(!/filter:/.test(rule('.vslide')), '.vslide без filter'); assert(/\.vimgs \.vsp\{filter:brightness/.test(CSS_VN)); ['.vact', '.vpp', '.vbr', '.vslide', '.vimgs', '.vbg'].forEach((s) => assert(!/(^|[;{])filter:/.test(rule(s)), s + ' без filter')); assert(!/\.vbr[^{]*\{[^}]*filter/.test(CSS_VN)); });
t('мобильное мерцание: дыхание/параллакс/Ken-Burns медленные (6–40 с), ease-in-out, без steps', () => { [['breathe', 6, 12], ['bgdrift', 6, 40], ['sildrift', 6, 40], ['kb', 6, 40]].forEach(([n, lo, hi]) => { const m = CSS_VN.match(new RegExp('animation:' + n + ' ([\\d.]+)s ([\\w-]+)')); assert(m, n); assert(+m[1] >= lo && +m[1] <= hi, n + ' длительность ' + m[1]); assert(m[2] === 'ease-in-out', n + ' easing'); }); assert(!/steps\(/.test(CSS_VN)); });
t('мобильное мерцание: reduced-motion — animation:none и без transform в transition-property, 0.01s нет нигде', () => { assert(!/animation-duration:\s*\.0*1s/.test(CSS_ALL + CSS_VN)); const m = CSS_ALL.match(/prefers-reduced-motion:reduce\)\{[\s\S]*?\n\}/)[0]; assert(/animation:none!important/.test(m)); assert(!/transform|translate|scale/.test(m.match(/transition-property:([^;]*);/)[1])); });
t('мобильное мерцание: resize-слушатель VN сглажен через rAF и отключает transition (адресная строка Android), холст частиц не пересоздаётся без смены размера', () => { assert(/requestAnimationFrame\(\(\) => \{ if \(finished\)/.test(JS_VN) && /nofx/.test(JS_VN) && /\.vstage\.nofx \.vact\{transition:opacity/.test(CSS_VN)); const fx = fs.readFileSync(path.join(__dirname, '../js/fx.js'), 'utf8'); assert(/F\.cv\.width === Math\.round\(w \* d\)/.test(fx) && /const k = dt \/ 16\.7/.test(fx)); });
t('мобильное мерцание: позиция актёра округляется до 0.5 px', () => assert(/Math\.round\(g\.x \* 2\) \/ 2/.test(JS_VN)));
t('лаги VN: пул декодированных картинок, look-ahead по репликам, показ после decode', () => { assert(/UI\.imgPool/.test(JS_VN) && /UI\.prefetch/.test(JS_VN) && /const ahead = \(n\)/.test(JS_VN) && /ahead\(3\)/.test(JS_VN) && /decode\(\)/.test(JS_VN)); });
t('лаги VN: кроссфейд настроений — не более 3 слоёв, ожидающие decode выбрасываются, старые слои снимаются по таймеру', () => { assert(/box\.children\.length > 2/.test(JS_VN) && /nw\.previousElementSibling\.remove/.test(JS_VN) && /classList\.contains\('on'\)\) c\.remove/.test(JS_VN)); });

console.log('Этап 2: характеристики');
t('8 основных характеристик, русские названия, 5 очков за уровень', () => { assert.deepStrictEqual(D.STATS, ['str', 'agi', 'vit', 'int', 'spi', 'wis', 'luk', 'cha']); ['Сила', 'Ловкость', 'Выносливость', 'Интеллект', 'Воля', 'Мудрость', 'Удача', 'Харизма'].forEach((n, i) => assert.strictEqual(D.STAT_N[D.STATS[i]], n)); assert.strictEqual(D.STAT_PER_LEVEL, 5); D.CLASS_IDS.forEach((c) => { const d = E.derive(mk(c)); D.STATS.forEach((k) => assert(d[k] > 0, c + ' ' + k)); }); });
t('очки характеристик: уровень 1 → 0, ур. 10 → 45; черновик применяется целиком, лишнее отвергается', () => { const s = mk(); assert.strictEqual(E.statFree(s.hero), 0); s.hero.level = 10; assert.strictEqual(E.statFree(s.hero), 45); assert.strictEqual(E.statCommit(s, { str: 46 }), 0); assert.strictEqual(E.statCommit(s, { zzz: 1 }), 0); assert.strictEqual(E.statCommit(s, { str: -1 }), 0); const s0 = E.derive(s).str; assert.strictEqual(E.statCommit(s, { str: 20, luk: 5 }), 25); assert.strictEqual(E.derive(s).str, s0 + 20); assert.strictEqual(E.statFree(s.hero), 20); });
t('сброс очков за золото: цена растёт с уровнем, золото списывается', () => { const s = mk(); s.hero.level = 20; E.statCommit(s, { agi: 10 }); const c = E.statRespecCost(s.hero); assert(c > 0); s.gold = c - 1; assert.strictEqual(E.statRespec(s), false); s.gold = c + 5; assert.strictEqual(E.statRespec(s), true); assert.strictEqual(s.gold, 5); assert.strictEqual(E.statSpent(s.hero), 0); assert.strictEqual(E.statFree(s.hero), 95); });
t('субстаты: все 20+ на месте, значения в пределах cap, крит растёт с Удачей, разбивка источников сходится', () => { assert(D.SUBS.length >= 21); const s = mk(); s.hero.level = 40; const a = E.derive(s); D.SUBS.forEach((def) => { const v = a.sub[def.id]; assert(Number.isFinite(v) && v >= def.cap[0] && v <= def.cap[1], def.id + '=' + v); }); E.statCommit(s, { luk: 150 }); const b = E.derive(s); assert(b.sub.crit > a.sub.crit && b.sub.drop >= a.sub.drop); const rows = E.subRows(s); assert.strictEqual(rows.length, D.SUBS.length); rows.forEach((r) => { assert(r.formula && r.parts); if (r.raw < r.cap[1] && r.raw > r.cap[0]) assert(Math.abs(r.raw - r.v) < 0.5, r.id + ' ' + r.raw + ' vs ' + r.v); }); });
t('стихии: 9 стихий + физика, сопротивление ≤ 75%, Пустота зовётся Энтропией', () => { const s = mk(); const rows = E.elemRows(s); assert.strictEqual(rows.length, 10); ['fire', 'ice', 'bolt', 'earth', 'wind', 'water', 'light', 'dark', 'arcane', 'phys'].forEach((e) => assert(rows.find((r) => r.id === e), e)); assert(/Пустота|Энтроп/.test(D.ELEMS.arcane.n)); s.hero.level = 100; E.statCommit(s, { spi: 495 }); E.elemRows(s).forEach((r) => assert(r.res <= 75 && r.res >= -50)); });
t('миграция v4 → v5: прогресс цел, alloc создан', () => { const p = S.migrate(JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/v3.json'), 'utf8'))); p.v = 4; const sl = p.slots[0]; delete sl.hero.alloc; sl.hero.level = 7; sl.gold = 123; const q = S.migrate(JSON.parse(JSON.stringify(p))); assert.strictEqual(q.v, 5); assert.deepStrictEqual(q.slots[0].hero.alloc, {}); assert.strictEqual(q.slots[0].hero.level, 7); assert.strictEqual(q.slots[0].gold, 123); assert(S.validate(q)); });
t('кап уровня 100, кривая опыта конечна и монотонна, мягкий рост', () => { assert.strictEqual(D.LEVEL_CAP, 100); let prev = 0; for (let l = 1; l < 100; l++) { const x = D.xpNeed(l); assert(Number.isFinite(x) && x > prev, 'xp ' + l); prev = x; } assert(D.xpNeed(99) / D.xpNeed(98) < 1.12); const s = mk(); E.addXp(s, 1e12); assert.strictEqual(s.hero.level, 100); });
t('враги: стихии (Церковь — свет, нежить — тьма), все навыки существуют, враги до ур. 100+', () => { let holy = 0, dark = 0; Object.keys(D.ENEMIES).forEach((id) => { const e = D.ENEMIES[id]; e.sk.forEach((k) => assert(D.ESK[k] || D.SKILLS[k], id + ' ' + k)); if (e.el === 'light') holy++; if (e.el === 'dark') dark++; }); assert(holy >= 5 && dark >= 8); const u = C.unitFromEnemy('gatekeeper', 130, 5, false, 'e0'); assert(u.maxHp > 0 && Number.isFinite(u.maxHp) && u.lv <= D.ENEMY_LV_CAP); });
t('бой: блок режет физический урон, двойной удар бьёт вдвое, точность съедает уклонение', () => { const hit = (mod) => { const s = mk('warrior'); s.hero.level = 10; const P = C.unitFromSlot(s), Tg = C.unitFromEnemy('rat', 10, 0, false, 'e0'); Tg.def = 0; Tg.eva = 0; Tg.hp = Tg.maxHp = 1e6; mod(P, Tg); const B = C.create([P], [Tg], E.rng(5), {}); P.spd = 999; const u = np(B, P); const hp0 = Tg.hp; C.act(B, u, { t: 'basic', tid: Tg.id }); return { B, d: hp0 - Tg.hp }; }; const base = hit(() => {}); const blk = hit((P, T) => { T.sub = Object.assign({}, T.sub, { blockCh: 100, blockPow: 50 }); }); assert(blk.B.ev.some((e) => e.s === 'Блок!')); assert(blk.d < base.d * 0.75, blk.d + ' vs ' + base.d); const dbl = hit((P) => { P.sub = Object.assign({}, P.sub, { dbl: 100 }); }); assert(dbl.B.ev.some((e) => e.s === 'Двойной удар!')); assert(dbl.d > base.d * 1.3); const ev1 = hit((P, T) => { T.eva = 70; P.sub = Object.assign({}, P.sub, { acc: 80 }); }); assert(!ev1.B.ev.some((e) => e.t === 'miss')); });
t('бой: вампиризм и закон «без крита» работают, крит у героя считается из субстатов', () => { const s = mk('rogue'); s.hero.level = 15; const d = E.derive(s); assert.strictEqual(d.crit, d.sub.crit); assert(Math.abs(d.critDmg - d.sub.critDmg / 100) < 1e-9); const P = C.unitFromSlot(s); assert(P.sub && P.sub.resEl); });
t('E.fmtBig: 1.2M, 3.4B, безопасно для NaN/∞', () => { assert.strictEqual(E.fmtBig(1234567), '1.2M'); assert.strictEqual(E.fmtBig(999), '999'); assert.strictEqual(E.fmtBig(NaN), '0'); assert(typeof E.fmtBig(Infinity) === 'string'); });

console.log('Этап 3: древо Силы, концепты, эффекты');
const tH = (lv, nodes, foes, seed) => { const s = mk(); s.hero.level = lv; s.hero.spent = {}; (nodes || []).forEach((id) => { s.hero.spent[id] = D.NODE_BY_ID[id].max; }); const P = C.unitFromSlot(s); P.spd = 12; const F = (foes || [['rat', lv]]).map((f, i) => { const e = C.unitFromEnemy(f[0], f[1], 0, false, 'e' + i); e.spd = 10; e.hp = e.maxHp = f[2] || 1e7; return e; }); const B = C.create([P], F, E.rng(seed || 3), {}); P.gauge = 100; return { s, P, F, B }; };
const heroTurn = (B, P) => { for (let i = 0; i < 80; i++) { const u = C.next(B); if (u === P) return P; if (B.over) return null; } return null; };
const castC = (B, P, id, tid) => { heroTurn(B, P); P.mp = P.maxMp; P.rc = P.rcMax; delete P.cds[id]; if (!P.sk.includes(id)) P.sk.push(id); return C.act(B, P, { t: 'skill', id, tid }); };
t('древо: связи существуют, ярусы по возрастанию, уровни до 100, все навыки и моды описаны', () => { const ids = new Set(T.nodes.map((n) => n.id)); assert.strictEqual(ids.size, T.nodes.length); T.nodes.forEach((n) => { n.req.forEach((q) => { assert(ids.has(q), n.id + '<-' + q); assert(D.NODE_BY_ID[q].lv <= n.lv && D.NODE_BY_ID[q].t <= n.t, n.id + ' порядок'); }); if (n.e.unlock) assert(D.SKILLS[n.e.unlock], n.id + ' навык ' + n.e.unlock); if (n.e.m) Object.keys(n.e.m).forEach((k) => assert(D.MODN[k] || D.MODN[k.replace(/^dmg_|^res_/, 'dmg_')] || /^(dmg|res)_/.test(k), 'MODN ' + k)); if (n.rr) Object.keys(n.rr).forEach((q) => assert(ids.has(q))); if (n.fuse) n.fuse.forEach((q) => assert(ids.has(q))); }); assert.strictEqual(Math.max(...T.nodes.map((n) => n.lv)), 100); });
t('древо: любой узел достижим из корня ветки, на ур. 100 хватает очков на большой билд, но не на всё', () => { let total = 0; T.nodes.forEach((n) => { total += n.max; const seen = new Set(); const up = (id) => { if (seen.has(id)) return; seen.add(id); D.NODE_BY_ID[id].req.forEach(up); }; up(n.id); assert([...seen].some((q) => !D.NODE_BY_ID[q].req.length), n.id); }); const s = mk(); s.hero.level = 100; assert(E.sp(s.hero) >= 200 && E.sp(s.hero) < total / 2, E.sp(s.hero) + ' vs ' + total); });
t('концептуальные навыки: ≥ 20 новых, у всех русское описание и лор, 25+ узлов-концептов', () => { const cs = Object.keys(D.SKILLS).filter((k) => /^c_/.test(k)); assert(cs.length >= 20, String(cs.length)); cs.forEach((k) => assert(D.SKILLS[k].conc && /[а-я]/.test(D.SKILLS[k].d) && D.SKILLS[k].n, k)); assert(D.CONCEPT_NODES.length >= 28, String(D.CONCEPT_NODES.length)); D.CONCEPT_NODES.forEach((id) => { const n = D.NODE_BY_ID[id]; assert(n.d && n.lore, id + ' нет описания/лора'); }); ['Мантра Силы', 'Стирание', 'Пожирание', 'Подчинение', 'Закон Короля', 'Остановка времени', 'Обращение урона', 'Бессмертие до конца хода', 'Вторая жизнь', 'Приказ мира'].forEach((nm) => assert(T.nodes.some((n) => n.n === nm), nm)); });
t('концепты открываются на высоких уровнях (20…100) и есть Преображения имба-навыков', () => { const lv = D.CONCEPT_NODES.map((id) => D.NODE_BY_ID[id].lv); [30, 40, 50, 60, 70, 80, 100].forEach((x) => assert(lv.some((v) => v >= x && v <= x + 9), 'ур. ' + x)); const tf = T.nodes.filter((n) => n.fuse && n.concept && n.rr); assert(tf.length >= 3); tf.forEach((n) => { const s = mk(); s.hero.level = 100; const old = D.NODE_BY_ID[n.fuse[0]]; assert(E.canLearn(s.hero, n.id)); s.hero.spent = {}; for (const q in n.rr) s.hero.spent[q] = n.rr[q] - 1; assert(/ранг/.test(E.canLearn(s.hero, n.id)), n.id); }); });
t('Преображение: «Распад бытия» → «Стирание» отключает старый навык, включает новый', () => { const s = mk(); s.hero.level = 100; const chain = ['E1', 'E2', 'E3', 'E4']; chain.forEach((q) => { s.hero.spent[q] = 1; }); s.hero.spent.E17 = 3; assert(E.skillsOf(s.hero).includes('k_unmake')); ['E6', 'E7', 'E5', 'E8'].forEach((q) => { s.hero.spent[q] = 1; }); ['E12', 'E9', 'E10', 'E11', 'E18'].forEach((q) => { s.hero.spent[q] = 1; }); s.hero.spent.E20 = 1; s.hero.spent.E23 = 1; s.hero.spent.E25 = 1; const ids = E.skillsOf(s.hero); assert(ids.includes('c_erase') && !ids.includes('k_unmake')); });
t('пассивки мощные: дерево даёт ≥ ×2 к урону при разумном билде на 100-м уровне', () => { const s = mk(); s.hero.level = 100; const d0 = E.derive(s); const top = ['R25', 'R29', 'R31', 'R34', 'P29', 'D29', 'E29', 'C27', 'B27', 'T25', 'M27']; top.forEach((id) => { s.hero.spent[id] = D.NODE_BY_ID[id].max; }); const d1 = E.derive(s); assert(d1.mods.dmgMul >= 100, 'dmgMul ' + d1.mods.dmgMul); assert(d1.atk > d0.atk * 1.2); assert(d1.critDmg > d0.critDmg + 0.4); assert((d1.mods.lifesteal || 0) >= 8); });
t('масштабирование от уровня и характеристик: dmgPerWil/dmgPerInt/dmgPerLv растут с Волей, Интеллектом и уровнем', () => { const mkS = (lv, alloc) => { const s = mk(); s.hero.level = lv; s.hero.spent = { R20: 3, R21: 3, R23: 3 }; if (alloc) s.hero.alloc = alloc; return E.derive(s).mods.dmg; }; assert(mkS(60, { spi: 100 }) > mkS(60) + 5); assert(mkS(100) > mkS(40)); assert(mkS(60, { int: 100 }) > mkS(60)); });
t('dmgMul перемножается, killStack/growDmg/foeDmg усиливают урон', () => { const hit = (mods, setupFn) => { const { P, F, B } = tH(20, [], [['rat', 20], ['bat', 20]]); Object.assign(P.mods, mods); P.crit = 0; F.forEach((e) => { e.def = 0; e.eva = 0; }); if (setupFn) setupFn(P, F, B); heroTurn(B, P); const hp = F[0].hp; C.act(B, P, { t: 'basic', tid: F[0].id }); return hp - F[0].hp; }; const base = hit({}); assert(hit({ dmgMul: 100 }) > base * 1.7); assert(hit({ killStack: 10 }, (P) => { P.kills = 5; }) > base * 1.3); assert(hit({ growDmg: 10 }, (P) => { P.turns = 9; }) > base * 1.5); assert(hit({ foeDmg: 20 }) > base * 1.25); });
t('c_stop: враги (даже босс) пропускают ход, Король ходит снова', () => { const { P, F, B } = tH(60, [], [['rat', 60], ['gatekeeper', 60]]); F[1].role = 'boss'; castC(B, P, 'c_stop'); assert(F.every((f) => f.st.some((x) => x.id === 'stop'))); assert(P.gauge >= 100, 'лишний ход ' + P.gauge); const u = C.next(B); assert.strictEqual(u, P); assert(!F.some((f) => f.hp < f.maxHp), 'враги не ходили'); });
t('c_law: враги без критов, контроля, лечения и призыва; закон истекает', () => { const { P, F, B } = tH(60, [], [['rat', 60]]); castC(B, P, 'c_law'); assert(B.law.nocrit > 0 && B.law.noctrl > 0 && B.law.noheal > 0 && B.law.nosummon > 0); const e = F[0]; e.crit = 100; e.atk = 50; P.eva = 0; P.def = 0; for (let i = 0; i < 6; i++) { const hp0 = P.hp; B.cur = e; B.units.forEach((u) => { u.gauge = 0; }); e.gauge = 100; B.cur = null; const x = C.next(B); if (x === P) C.act(B, P, { t: 'guard' }); } assert(!B.ev.some((q) => q.t === 'dmg' && q.from === e.id && q.crit), 'крит врага запрещён'); for (let i = 0; i < 12 && B.law.nocrit > 0; i++) { const x = C.next(B); if (x === P) C.act(B, P, { t: 'guard' }); } assert(!B.law.nocrit, 'закон закончился'); });
t('c_erase: слабого стирает мгновенно, босса — лишь 12% здоровья, здорового — урон', () => { const { P, F, B } = tH(70, [], [['rat', 70], ['rat', 70], ['gatekeeper', 70]]); F[0].hp = Math.round(F[0].maxHp * 0.3); F[2].role = 'boss'; castC(B, P, 'c_erase', F[0].id); assert(!F[0].alive, 'стёрт'); P.cds.c_erase = 0; castC(B, P, 'c_erase', F[1].id); assert(F[1].alive && F[1].hp < F[1].maxHp, 'здоровый — просто урон'); P.cds.c_erase = 0; const h0 = F[2].hp; castC(B, P, 'c_erase', F[2].id); assert(F[2].alive && h0 - F[2].hp <= F[2].maxHp * 0.121 + 1, 'босс'); });
t('c_devour: пожирает слабого, лечит, копит бонус урона', () => { const { P, F, B } = tH(60, [], [['rat', 60], ['rat', 60]]); F[0].hp = Math.round(F[0].maxHp * 0.2); P.hp = Math.round(P.maxHp * 0.4); castC(B, P, 'c_devour', F[0].id); assert(!F[0].alive && P.devStack === 1 && P.hp > P.maxHp * 0.6, P.hp + '/' + P.maxHp); });
t('c_thrall: подчинённый враг 3 хода бьёт своих; боссы могут сопротивляться', () => { const { P, F, B } = tH(60, [], [['rat', 60], ['bat', 60]]); castC(B, P, 'c_thrall', F[0].id); assert(F[0].st.some((x) => x.id === 'dominate' && x.dur === 3)); let hits = 0; for (let i = 0; i < 12; i++) { const x = C.next(B); if (x === P) C.act(B, P, { t: 'guard' }); } assert(F[1].hp < F[1].maxHp, 'союзник получил урон от подчинённого'); });
t('c_mirror: часть урона не доходит до героя, а возвращается врагу', () => { const { P, F, B } = tH(60, [], [['rat', 60]]); castC(B, P, 'c_mirror'); const e = F[0], hp0 = e.hp; e.crit = 0; e.gauge = 100; P.gauge = 0; P.eva = 0; P.sub.statRes = 0; const r = C.has(P, 'reflect'); assert(r && r.pow === 0.6); P.hp = P.maxHp; const php = P.hp; for (let i = 0; i < 10 && P.hp === php; i++) { const x = C.next(B); if (x === P) C.act(B, P, { t: 'guard' }); } assert(e.hp < hp0, 'отражено'); });
t('c_immortal: цена 25% HP, один раз за бой, HP не падает ниже 1, расплата по окончании', () => { const { P, F, B } = tH(60, [], [['rat', 60]]); const m = P.maxHp; castC(B, P, 'c_immortal'); assert(P.hp <= m * 0.76, 'цена'); assert(P.cds.c_immortal >= 99, 'один раз'); P.hp = 5; F[0].atk = 1e6; let guard = 0; while (C.has(P, 'immortal') && guard++ < 20) { const x = C.next(B); if (x === P) { C.act(B, P, { t: 'guard' }); } } assert(P.immDebt >= 0); assert(guard > 0); });
t('Вторая жизнь: раз за бой возвращает 65% HP и даёт бессмертие на 2 хода', () => { const { P, F, B } = tH(60, ['P33'], [['rat', 60]]); assert(P.mods.secondLife >= 2); P.hp = 3; P.mods.reviveFull = 0; P.eva = 0; F[0].gauge = 100; P.gauge = 0; F[0].eva = 0; for (let i = 0; i < 6 && !B.over; i++) { const x = C.next(B); if (x === P) C.act(B, P, { t: 'guard' }); if (P.slUsed) break; } assert(P.slUsed && P.alive && P.hp >= 1 && B.ev.some((q) => q.t === 'revive') && (C.has(P, 'immortal') || P.hp > 1)); });
t('c_decree: шкала хода врагов отброшена, они уязвимы и ослаблены', () => { const { P, F, B } = tH(70, [], [['rat', 70], ['bat', 70]]); F.forEach((f) => { f.gauge = 80; }); castC(B, P, 'c_decree'); F.forEach((f) => { assert(f.gauge <= -60 + 1e-6 || f.gauge < 0, 'gauge ' + f.gauge); assert(C.has(f, 'vuln') && C.has(f, 'weak')); }); });
t('c_silence: враги только бьют обычным ударом на 3 хода', () => { const { P, F, B } = tH(40, [], [['gatekeeper', 40]]); castC(B, P, 'c_silence'); assert(B.law.nocast > 0); for (let i = 0; i < 6; i++) { const x = C.next(B); if (x === P) C.act(B, P, { t: 'guard' }); } const sk = B.ev.filter((q) => q.t === 'skill' && q.tg && q.tg.length && q.u === F[0].id); assert(sk.every((q) => q.id === 'basic' || q.n === 'Удар'), JSON.stringify(sk.slice(0, 3))); });
t('c_echo: повторяет последний навык бесплатно и слабее', () => { const { P, F, B } = tH(60, [], [['rat', 60]]); F[0].def = 0; F[0].eva = 0; P.crit = 0; castC(B, P, 'k_smite', F[0].id); const d1 = F[0].maxHp - F[0].hp; P.cds.c_echo = 0; heroTurn(B, P); const mp0 = P.mp = P.maxMp; const hp1 = F[0].hp; C.act(B, P, { t: 'skill', id: 'c_echo' }); const d2 = hp1 - F[0].hp; assert(d2 > 0 && d2 < d1 * 1.2, d1 + ' / ' + d2); assert(P.mp >= mp0 - C.mpCost(P, D.SKILLS.c_echo) - 1, 'эхо бесплатно'); });
t('c_eye + markCrit: удар по меченому всегда критический', () => { const { P, F, B } = tH(60, ['B19'], [['rat', 60]]); assert(P.mods.markCrit > 0); P.crit = 0; F[0].eva = 0; castC(B, P, 'c_eye', F[0].id); assert(B.ev.filter((q) => q.t === 'dmg' && q.from === P.id).every((q) => q.crit)); });
t('c_pact: цена здоровья, +80% урона, возврат здоровья', () => { const { P, F, B } = tH(60, [], [['rat', 60]]); const m = P.maxHp; castC(B, P, 'c_pact'); assert(P.hp <= m * 0.71 && C.has(P, 'pact')); const hp = P.hp; heroTurn(B, P); C.act(B, P, { t: 'basic', tid: F[0].id }); assert(P.hp > hp, 'вампиризм договора'); });
t('c_blades: 12 ударов; c_sever снимает баффы и раскалывает броню', () => { const { P, F, B } = tH(60, [], [['rat', 60], ['bat', 60]]); F[0].eva = F[1].eva = 0; P.sub.dbl = 0; castC(B, P, 'c_blades'); assert.strictEqual(B.ev.filter((q) => q.t === 'dmg' && q.from === P.id).length, 12); C.addSt(B, P, F[0], 'haste', 3); C.addSt(B, P, F[0], 'shield', 3, 99); castC(B, P, 'c_sever'); F.forEach((f) => assert(C.has(f, 'sunder'))); assert(!C.has(F[0], 'haste') && !C.has(F[0], 'shield')); });
t('Присутствие Тирана: враги слабее с первой секунды и отброшены назад по шкале', () => { const { s, P, F, B } = tH(60, [], [['rat', 60]]); const s2 = mk(); s2.hero.level = 60; s2.hero.spent = { T21: 2 }; const P2 = C.unitFromSlot(s2); const e = C.unitFromEnemy('rat', 60, 0, false, 'e0'); const g0 = e.gauge; const B2 = C.create([P2], [e], E.rng(1), {}); assert(C.has(e, 'tyrant')); assert(e.gauge < 20, 'gauge ' + e.gauge); });
t('Мантры: Мантра Разума удваивает магию и сопротивление, Мантра Мгновения ускоряет, предел ограничен', () => { const { P, F, B } = tH(60, ['M24', 'M26'], [['rat', 60]]); const mag0 = P.mag, res0 = P.res, spd0 = P.spd; for (let i = 0; i < 6; i++) { heroTurn(B, P); C.act(B, P, { t: 'guard' }); } assert.strictEqual(P.mgs, 3); assert(Math.abs(P.mag - mag0 * 8) < 1, P.mag + ' vs ' + mag0 * 8); assert(P.res >= res0 * 8 - 1); const { P: P2, B: B2 } = tH(60, [], [['rat', 60]]); assert(!P2.m0); const sP = mk(); sP.hero.level = 60; sP.hero.spent = { P14: 1, P15: 2, P10: 3, P12: 3 }; const U = C.unitFromSlot(sP); assert(U.mods.mantra > 0); });
t('Мантра Силы сохранена: удваивает атаку и броню каждый ход, значения считаются от значений ДО боя', () => { const sP = mk(); sP.hero.level = 40; sP.hero.spent = { P14: 1 }; const e = C.unitFromEnemy('rat', 5, 0, false, 'e0'); e.hp = e.maxHp = 1e9; e.spd = 1; const U = C.unitFromSlot(sP); U.spd = 40; const atk0 = U.atk, def0 = U.def; const B = C.create([U], [e], E.rng(2), {}); U.gauge = 100; for (let i = 0; i < 3; i++) { heroTurn(B, U); C.act(B, U, { t: 'guard' }); } assert(U.mst >= 3 && U.mods.mantra >= 3); assert(Math.abs(U.atk - atk0 * Math.pow(2, U.mst)) < 1); assert(Math.abs(U.def - def0 * Math.pow(2, U.mst)) < 1); const U2 = C.unitFromSlot(sP); assert(Math.abs(U2.atk - atk0) < 1, 'после боя значения прежние'); });
t('безопасные числа: билд на максимум не даёт NaN/Infinity, урон ограничен, fmtBig форматирует', () => { const s = mk(); s.hero.level = 100; T.nodes.forEach((n) => { s.hero.spent[n.id] = n.max; }); s.hero.alloc = { str: 495 }; const d = E.derive(s); ['maxHp', 'maxMp', 'atk', 'mag', 'def', 'res', 'spd', 'crit', 'critDmg', 'eva'].forEach((k) => assert(Number.isFinite(d[k]), k)); const P = C.unitFromSlot(s); const e = C.unitFromEnemy('rat', 100, 5, false, 'e0'); e.spd = 1; const B = C.create([P], [e], E.rng(2), {}); P.gauge = 100; heroTurn(B, P); P.mst = 12; C.act(B, P, { t: 'basic', tid: e.id }); B.ev.filter((q) => q.t === 'dmg').forEach((q) => assert(Number.isFinite(q.v) && q.v <= 9e12)); assert(/^\d/.test(E.fmtBig(d.maxHp))); });
t('нет бессмертия без цены: ни один навык/пассивка не даёт неуязвимость без расплаты', () => { const imm = Object.values(D.SKILLS).filter((k) => k.fx.some((f) => f.k === 'st' && f.id === 'immortal')); imm.forEach((k) => assert(k.hpCost > 0 && k.cd >= 99, k.id + ' бессмертие без цены/одно за бой')); assert(D.NODE_BY_ID.P33.e.m.secondLife); const s = mk(); s.hero.level = 100; s.hero.spent.P33 = 1; const P = C.unitFromSlot(s); const e = C.unitFromEnemy('rat', 100, 0, false, 'e0'); e.atk = 1e9; e.spd = 40; const B = C.create([P], [e], E.rng(2), {}); let g = 0; while (!B.over && g++ < 40) { const x = C.next(B); if (x === P) C.act(B, P, { t: 'basic', tid: e.id }); } assert(B.over === 'lose', 'вторая жизнь — только один раз'); });
t('имба-навыки доступны рано и сильны: ≥ 12 активных, множители ×2.8…×8.5, у каждого цена и КД', () => { const ks = Object.values(D.SKILLS).filter((k) => /^k_(wrath|rampage|titan|abyss|spear|unmake|edict|feast|chant|maw|flurry|bladestorm|oppress)$/.test(k.id)); assert.strictEqual(ks.length, 13); ks.forEach((k) => assert(k.mp && k.cd, k.id)); const mx = Math.max(...ks.map((k) => Math.max(...k.fx.filter((f) => f.k === 'dmg').map((f) => f.m * (f.hits && k.tgt !== 'rfoe' ? f.hits : 1), 0)))); assert(mx >= 8.5); const early = T.nodes.filter((n) => n.e.unlock && /^k_/.test(n.e.unlock) && n.lv <= 10 && D.SKILLS[n.e.unlock] && ks.includes(D.SKILLS[n.e.unlock])); assert(early.length >= 7, String(early.length)); });
t('миграция сохранения со старыми узлами дерева: прогресс R*/P*/D*/E*/V*/C* жив', () => { const s = mk(); s.hero.level = 30; s.hero.spent = { R1: 5, P1: 2, P14: 1, D2: 1, E5: 2, V4: 1, C2: 1 }; const p = S.migrate(JSON.parse(JSON.stringify({ v: 4, active: 0, slots: [s] }))); const sp = p.slots[0].hero.spent; assert.deepStrictEqual(sp, s.hero.spent); assert(E.skillsOf(p.slots[0].hero).includes('k_bolt')); });

console.log(`\nТесты: ${pass} ✓, ${fail} ✗`);
if (fail) { console.log(failed.join('\n')); process.exit(1); }
