/* Юнит-тесты логики (node, без зависимостей). Запуск: npm test */
const fs = require('fs'), path = require('path'), assert = require('assert');
const RPG = require('../js/data-core.js');
['data-prof', 'data-world', 'data-story', 'portrait', 'engine', 'combat', 'save'].forEach((f) => require('../js/' + f + '.js'));
const { D, E, C, S } = RPG;
let pass = 0, fail = 0; const failed = [];
const t = (name, fn) => { try { fn(); pass++; } catch (e) { fail++; failed.push(name + ': ' + e.message); console.log('  ✗', name, '\n     ', e.message); } };
const mk = (cls, o) => E.newSlot(Object.assign({ name: 'Тест', sex: 'm', race: 'human', cls, portrait: 'human_m_1', uniq: 'phoenix', prof1: 'smith', prof2: 'miner' }, o || {}));
const mem = () => { const m = {}; return { getItem: (k) => (k in m ? m[k] : null), setItem: (k, v) => { m[k] = String(v); }, removeItem: (k) => { delete m[k]; }, _m: m }; };
const np = (B, only) => { for (let i = 0; i < 400; i++) { const u = C.next(B); if (u && (!only || u === only)) return u; if (B.over) return null; if (u && only) C.act(B, u, { t: 'guard' }); } throw new Error('нет хода игрока'); };
const autoBattle = (B, limit) => { let n = 0; while (!B.over && n++ < (limit || 3000)) { const u = C.next(B); if (u) C.act(B, u, C.choose(B, u)); } return n; };

console.log('Данные');
t('5 классов с нужными названиями', () => assert.deepStrictEqual(D.CLASS_IDS.map((c) => D.CLASSES[c].n), ['Воин', 'Маг', 'Вор', 'Целитель', 'Щитоносец']));
t('минимум 5 рас с пассивом и лором', () => { assert(Object.keys(D.RACES).length >= 5); Object.values(D.RACES).forEach((r) => { assert(r.pn && r.pd && r.lore && r.st); }); });
t('30 портретов: 5 рас × 2 пола × 3 варианта, уникальные id', () => { assert.strictEqual(RPG.PORTRAITS.length, 30); assert.strictEqual(new Set(RPG.PORTRAITS.map((p) => p.id)).size, 30); RPG.RACE_IDS.forEach((r) => ['m', 'f'].forEach((s) => assert.strictEqual(RPG.PORTRAITS.filter((p) => p.race === r && p.sex === s).length, 3))); });
t('файлы портретов существуют (30 героев + NPC)', () => { RPG.PORTRAITS.forEach((p) => assert(fs.existsSync(path.join(__dirname, '../assets/portraits', p.id + '.webp')), p.id)); Object.keys(RPG.NPC_LOOK).forEach((k) => ['n', 'h', 's', 'x'].forEach((m) => assert(fs.existsSync(path.join(__dirname, '../assets/portraits', `npc_${k}_${m}.webp`)), k + m))); });
t('SVG-портрет генерируется для всех', () => RPG.PORTRAITS.forEach((p) => assert(RPG.portraitSVG(Object.assign({ mood: 'n' }, p)).startsWith('<svg'))));
t('у каждого класса ≥15 узлов, 3 ветки, стартовые навыки существуют', () => D.CLASS_IDS.forEach((c) => { const T = D.TREES[c]; assert(T.nodes.length >= 15, c); assert.strictEqual(T.branches.length, 3); D.CLASSES[c].start.forEach((s) => assert(D.SKILLS[s], s)); }));
t('деревья: предусловия существуют, нет циклов, уровни растут по ярусам', () => {
  const check = (nodes, tag) => { const ids = new Set(nodes.map((n) => n.id)); assert.strictEqual(ids.size, nodes.length, 'дубликаты ' + tag); nodes.forEach((n) => { n.req.forEach((q) => { assert(ids.has(q), tag + ' req ' + q); const p = nodes.find((x) => x.id === q); assert(p.t < n.t, tag + ' ярус ' + n.id); }); assert(n.max >= 1); assert(n.lv >= 1); }); };
  D.CLASS_IDS.forEach((c) => check(D.TREES[c].nodes, c)); D.UNIQ_IDS.forEach((u) => check(D.UNIQ[u].nodes, u));
});
t('узлы-разблокировки ссылаются на существующие навыки; в дереве хватает навыков', () => D.CLASS_IDS.forEach((c) => { const un = D.TREES[c].nodes.filter((n) => n.e.unlock); assert(un.length >= 3, c + ' навыков в дереве'); un.forEach((n) => assert(D.SKILLS[n.e.unlock], n.e.unlock)); }));
t('≥8 уникальных навыков, у каждого ≥6 узлов и несколько рангов', () => { assert(D.UNIQ_IDS.length >= 8); D.UNIQ_IDS.forEach((u) => { const U = D.UNIQ[u]; assert(U.nodes.length >= 6, u); assert(U.nodes.some((n) => n.max >= 3), u); assert(D.SKILLS['u_' + u], u); assert(U.act && U.act.fx); }); });
t('≥8 профессий; крафт и добыча; перки на 5/10/15/20', () => { assert(D.PROF_IDS.length >= 8); assert(D.PROF_IDS.filter((p) => D.PROFS[p].t === 'craft').length >= 5); assert(D.PROF_IDS.filter((p) => D.PROFS[p].t === 'gather').length >= 3); D.PROF_IDS.forEach((p) => assert.deepStrictEqual(Object.keys(D.PROFS[p].perks), ['5', '10', '15', '20'])); });
t('рецепты: материалы существуют, у каждой крафт-профессии есть рецепты', () => { D.buildRecipes(); D.RECIPES.forEach((r) => Object.keys(r.mats).forEach((m) => assert(D.MATS[m], r.id + ' ' + m))); D.PROF_IDS.filter((p) => D.PROFS[p].t === 'craft').forEach((p) => assert(D.recipesFor(p).length >= (p === 'cook' ? 5 : 8), p)); });
t('≥5 подземелий: враги, мини-босс, босс существуют, ≥2 этажа', () => { assert(D.DUNGEONS.length >= 5); D.DUNGEONS.forEach((d) => { assert(d.floors >= 2); d.pool.forEach((e) => assert(D.ENEMIES[e], e)); assert(D.ENEMIES[d.mini] && D.ENEMIES[d.boss]); [].concat(...d.pool.map((e) => D.ENEMIES[e].sk), D.ENEMIES[d.boss].sk, D.ENEMIES[d.mini].sk).forEach((s) => assert(D.ESK[s], s)); }); });
t('4 уровня сложности', () => assert.strictEqual(D.TIERS.length, 4));

console.log('Характеристики и экипировка');
t('стартовые характеристики классов различаются и положительны', () => { const sig = new Set(); D.CLASS_IDS.forEach((c) => { const d = E.derive(mk(c)); assert(d.maxHp > 0 && d.maxMp > 0 && d.spd > 0); sig.add([d.str, d.agi, d.int, d.vit, d.spi].join()); }); assert.strictEqual(sig.size, 5); });
t('Воин физически сильнее, Маг — магически, Целитель — лечит, Щитоносец — крепче', () => { const d = {}; D.CLASS_IDS.forEach((c) => d[c] = E.derive(mk(c, { race: 'human' }))); assert(d.warrior.atk > d.mage.atk); assert(d.mage.mag > d.warrior.mag); assert(d.healer.hpow > d.warrior.hpow); assert(d.shield.def > d.mage.def && d.shield.maxHp > d.mage.maxHp); assert(d.rogue.spd >= d.warrior.spd); });
t('расовые бонусы применяются', () => { const a = E.derive(mk('warrior', { race: 'human' })), b = E.derive(mk('warrior', { race: 'dwarf' })); assert(a.str !== b.str || a.vit !== b.vit || a.maxHp !== b.maxHp); const c = E.collect(mk('warrior', { race: 'human' })); assert(c.mods.xp > 0 || c.mods.gold > 0); });
t('рост уровня повышает характеристики', () => { const s = mk('mage'); const d1 = E.derive(s); s.hero.level = 10; const d2 = E.derive(s); assert(d2.maxHp > d1.maxHp && d2.mag > d1.mag); });
t('экипировка увеличивает урон/броню; улучшение даёт +9%/ур.', () => { const s = mk('warrior'), rng = E.rng(5); const d0 = E.derive(s); const it = E.genItem(rng, { base: 'body_h', il: 6, rarity: 2 }); E.addItem(s, it); E.equip(s, it.id); const d1 = E.derive(s); assert(d1.def > d0.def); s.gold = 99999; E.addMat(s, 'ing_cu', 50); const r = E.upgrade(s, it); assert.strictEqual(r, ''); assert(E.derive(s).def >= d1.def); });
t('классы не могут носить чужое оружие', () => { const s = mk('mage'), w = E.genItem(E.rng(1), { base: 'sword', il: 3, rarity: 0 }); E.addItem(s, w); assert.notStrictEqual(E.equip(s, w.id), ''); const st = E.genItem(E.rng(2), { base: 'staff', il: 3, rarity: 0 }); E.addItem(s, st); assert.strictEqual(E.equip(s, st.id), ''); });
t('перки профессий дают бонусы с нужного уровня', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); const g0 = E.collect(s).mods.gear || 0; s.profs.smith.lv = 5; assert(E.collect(s).mods.gear > g0); });
t('опыт и уровни: кап 30, очки навыков = уровень−1', () => { const s = mk('warrior'); E.addXp(s, 1e9); assert.strictEqual(s.hero.level, D.LEVEL_CAP); assert.strictEqual(E.sp(s.hero), D.LEVEL_CAP - 1); assert(D.xpNeed(10) > D.xpNeed(5)); });

console.log('Древа навыков');
t('нельзя изучить без очков / без уровня / без предусловия', () => { const s = mk('warrior'), h = s.hero; assert(E.learn(h, 'wA1')); h.level = 2; assert.strictEqual(E.learn(h, 'wA1'), ''); const T = D.TREES.warrior.nodes.find((n) => n.req.length && n.lv > 1 && !n.req.includes('wA1')); h.level = 30; assert(E.canLearn(h, T.id), 'без предусловия нельзя'); });
t('изучение ранга, максимум ранга, трата очков', () => { const s = mk('warrior'), h = s.hero; h.level = 30; const n = D.TREES.warrior.nodes.find((x) => !x.req.length && x.max >= 2); for (let i = 0; i < n.max; i++) assert.strictEqual(E.learn(h, n.id), ''); assert(E.learn(h, n.id)); assert.strictEqual(h.spent[n.id], n.max); assert.strictEqual(E.sp(h), 29 - n.max); });
t('можно изучить ВСЕ узлы класса за 30 уровней (≥ очков не хватает не должно)', () => D.CLASS_IDS.forEach((c) => { const total = D.TREES[c].nodes.reduce((a, n) => a + n.max, 0); assert(total >= 26 && total <= 80, c + ' ' + total); }));
t('разблокировка навыка добавляет его в список', () => { const s = mk('warrior'), h = s.hero; h.level = 30; const n = D.TREES.warrior.nodes.find((x) => x.e.unlock && !x.req.length); if (n) { E.learn(h, n.id); assert(E.skillsOf(h).includes(n.e.unlock)); } else { const first = D.TREES.warrior.nodes.find((x) => x.e.unlock); h.spent[first.id] = 1; assert(E.skillsOf(h).includes(first.e.unlock)); } });
t('узлы улучшают характеристики', () => { const s = mk('warrior'), h = s.hero; h.level = 30; const n = D.TREES.warrior.nodes.find((x) => x.e.m && !x.req.length); const d0 = E.collect(s).mods; E.learn(h, n.id); const d1 = E.collect(s).mods; assert(Object.keys(n.e.m).some((k) => d1[k] > (d0[k] || 0))); });
t('искры Эха: 1 за 3 уровня + за босса; Эхо-узлы тратят их', () => { const s = mk('mage', { uniq: 'frostheart' }), h = s.hero; assert.strictEqual(E.up(h), 0); h.level = 6; h.bossPts = 1; assert.strictEqual(E.up(h), 3); const U = D.UNIQ.frostheart.nodes.find((n) => !n.req.length && n.lv <= 6); assert.strictEqual(E.learn(h, U.id), ''); assert.strictEqual(E.up(h), 2); });
t('сброс навыков за золото возвращает очки', () => { const s = mk('warrior'); s.hero.level = 10; E.learn(s.hero, 'wA1'); assert(E.respec(s, 'c') === false); s.gold = 1e5; assert(E.respec(s, 'c')); assert.strictEqual(E.sp(s.hero), 9); });
t('навык Эха в списке навыков героя', () => { const s = mk('rogue', { uniq: 'shadowdance' }); assert(E.skillsOf(s.hero).includes('u_shadowdance')); });

console.log('Бой');
const duel = (cls, enemy, lv) => { const s = mk(cls); s.hero.level = lv || 1; const P = C.unitFromSlot(s); const B = C.create([P], [C.unitFromEnemy(enemy, lv || 1, 0, false, 'e0')], E.rng(42), { auto: true }); return { B, P, s }; };
t('бой детерминирован при одинаковом seed', () => { const run = () => { const { B } = duel('warrior', 'rat', 2); autoBattle(B); return B.log.join('|') + B.over; }; assert.strictEqual(run(), run()); });
t('первый ход и порядок по скорости: быстрые ходят чаще', () => { const { B, P } = duel('rogue', 'rat', 1); B.opts.auto = false; P.spd = 40; B.foes[0].spd = 10; B.foes[0].hp = B.foes[0].maxHp = 1e6; const order = []; let lr = 0; for (let i = 0; i < 400 && order.length < 30 && !B.over; i++) { const u = C.next(B); if (B.cur && B.round !== lr) { lr = B.round; order.push(B.cur.side); } if (u) C.act(B, u, { t: 'guard' }); } assert(order.filter((x) => x === 'a').length > order.filter((x) => x === 'e').length); });
t('базовая атака наносит урон', () => { const { B, P } = duel('warrior', 'rat', 1); const e = B.foes[0]; const hp = e.hp; let u; u = np(B); C.act(B, u, { t: 'basic', tid: e.id }); assert(e.hp < hp || !e.alive); assert(B.ev.some((x) => x.t === 'dmg')); });
t('каждый класс побеждает слабого врага автобоем', () => D.CLASS_IDS.forEach((c) => { const { B } = duel(c, 'rat', 3); autoBattle(B); assert.strictEqual(B.over, 'win', c); }));
t('реакции стихий: мокрый + молния усиливает урон', () => {
  const { B, P } = duel('mage', 'slime', 5); const e = B.foes[0]; e.weak = []; e.resist = []; e.def = 0; e.res = 0;
  const hit = (wet) => { const b = duel('mage', 'slime', 5); const en = b.B.foes[0]; en.weak = []; en.resist = []; en.def = 0; en.res = 0; en.hp = en.maxHp = 1e6; if (wet) C.addSt(b.B, b.P, en, 'wet', 3); b.B.rng = E.rng(9); let u; u = np(b.B); const id = b.P.sk.find((s) => D.SKILLS[s] && D.SKILLS[s].fx && D.SKILLS[s].fx.some((f) => f.el === 'bolt')) || 'm_bolt'; if (!D.SKILLS[id]) return null; b.P.mp = 99; C.act(b.B, u, { t: 'skill', id, tid: en.id }); return 1e6 - en.hp; };
  const boltId = D.CLASSES.mage.start.concat(D.TREES.mage.nodes.map((n) => n.e.unlock).filter(Boolean)).find((s) => D.SKILLS[s].fx.some((f) => f.el === 'bolt')); assert(boltId, 'нет навыка молнии');
  const run = (wet) => { const s = mk('mage'); s.hero.level = 5; D.TREES.mage.nodes.forEach((n) => { if (n.e.unlock) s.hero.spent[n.id] = 1; }); const P2 = C.unitFromSlot(s); const en = C.unitFromEnemy('slime', 5, 0, false, 'e0'); en.weak = []; en.resist = []; en.def = 0; en.res = 0; en.hp = en.maxHp = 1e7; const B2 = C.create([P2], [en], E.rng(3), {}); P2.crit = 0; P2.mp = 999; if (wet) C.addSt(B2, P2, en, 'wet', 3); let u; u = np(B2); C.act(B2, u, { t: 'skill', id: boltId, tid: 'e0' }); return 1e7 - en.hp; };
  const dry = run(false), wet = run(true); assert(wet > dry * 1.05, `dry ${dry} wet ${wet}`);
});
t('статусы: горение наносит урон каждый ход и истекает', () => { const { B, P } = duel('mage', 'rat', 3); B.opts.auto = false; const e = B.foes[0]; e.hp = e.maxHp = 1e5; C.addSt(B, P, e, 'burn', 2, 50); const hp = e.hp; for (let i = 0; i < 80 && !B.over; i++) { const u = C.next(B); if (u) C.act(B, u, { t: 'guard' }); } assert(e.hp < hp); assert(!e.st.find((s) => s.id === 'burn')); });
t('Щитоносец: провокация заставляет врага бить его', () => { const s = mk('shield'); const P = C.unitFromSlot(s); const ally = C.unitFromComp('tika', 3, 1); ally.id = 'tk'; const e = C.unitFromEnemy('wolf', 3, 0, false, 'e0'); const B = C.create([P, ally], [e], E.rng(8), {}); C.addSt(B, P, P, 'taunt', 3); e.intent = { id: e.sk[0], tid: ally.id }; const act = (function () { e.charging = null; return C.choose(B, e); })(); assert(act); const tg = ['taunt'].some((id) => C.has ? C.has(P, id) : P.st.find((x) => x.id === id)); assert(tg); });
t('Целитель лечит союзника', () => { const s = mk('healer'); s.hero.level = 5; const P = C.unitFromSlot(s); const ally = C.unitFromComp('kairen', 5, 0.3); const e = C.unitFromEnemy('rat', 3, 0, false, 'e0'); e.hp = e.maxHp = 1e6; const B = C.create([P, ally], [e], E.rng(11), {}); P.spd = 999; const hp = ally.hp; let u; u = np(B, P); P.mp = 99; C.act(B, u, { t: 'skill', id: 'h_heal', tid: ally.id }); assert(ally.hp > hp); });
t('Вор крадёт золото (steal) и ИИ врагов выбирает действия', () => { const { B } = duel('rogue', 'wolf', 4); autoBattle(B); assert(B.over); assert(B.log.length > 3); });
t('бой с боссом заканчивается (нет зацикливания) на всех классах', () => D.CLASS_IDS.forEach((c) => { const s = mk(c); s.hero.level = 8; const P = C.unitFromSlot(s); const K = C.unitFromComp('kairen', 8, 1), T = C.unitFromComp('tika', 8, 1); const B = C.create([P, K, T], [C.unitFromEnemy('gatekeeper', 4, 0, false, 'e0')], E.rng(77), { auto: true, noFlee: true }); const n = autoBattle(B); assert(B.over && n < 3000, c + ' ' + B.over); }));
t('враги намекают намерение; телеграфируемые атаки копятся', () => { const { B } = duel('warrior', 'gatekeeper', 4); const e = B.foes[0]; assert(e.intent && D.ESK[e.intent.id]); });
t('побег невозможен в боссе', () => { const { B, s } = duel('warrior', 'gatekeeper', 4); B.opts.noFlee = true; let u; u = np(B); C.act(B, u, { t: 'flee' }); assert.notStrictEqual(B.over, 'flee'); });
t('предметы в бою: зелье лечит, расходуется', () => { const s = mk('warrior'); s.cons.pot_hp1 = 2; const P = C.unitFromSlot(s); P.hp = 10; const e = C.unitFromEnemy('rat', 1, 0, false, 'e0'); const B = C.create([P], [e], E.rng(2), { cons: s.cons }); B.cons = s.cons; let u; u = np(B); C.act(B, u, { t: 'item', id: 'pot_hp1', tid: P.id }); assert(P.hp > 10); assert.strictEqual(s.cons.pot_hp1, 1); });
t('сложность повышает силу врагов', () => { const a = C.unitFromEnemy('wolf', 5, 0, false, 'e'), b = C.unitFromEnemy('wolf', 5, 3, false, 'e'); assert(b.maxHp > a.maxHp * 1.5 && b.atk > a.atk); });

console.log('Лут, магазин, вылазки');
t('редкости растут с удачей; легендарки получают имя', () => { const cnt = (luck) => { const r = E.rng(3); let n = 0; for (let i = 0; i < 4000; i++) if (E.rollRarity(r, luck, 0) >= 3) n++; return n; }; assert(cnt(2.2) > cnt(1)); const it = E.genItem(E.rng(4), { base: 'sword', il: 20, rarity: 4 }); assert(it.nm.includes('«')); });
t('характеристики предмета растут с редкостью и уровнем', () => { const v = (r, il) => E.itemScore(E.genItem(E.rng(1), { base: 'sword', il, rarity: r })); assert(v(4, 10) > v(2, 10) && v(2, 10) > v(0, 10) && v(0, 20) > v(0, 5)); });
t('цены: продажа < покупка; лучше предмет — дороже', () => { const a = E.genItem(E.rng(1), { base: 'sword', il: 5, rarity: 0 }), b = E.genItem(E.rng(1), { base: 'sword', il: 5, rarity: 3 }); assert(E.sellPrice(a) < E.buyPrice(a) && E.itemValue(b) > E.itemValue(a)); });
t('лавка: покупка списывает золото и добавляет предмет; нехватка золота — отказ', () => { const s = mk('warrior'); s.gold = 0; assert(E.buyShopItem(s, 0)); s.gold = 99999; const n = s.inv.length; assert.strictEqual(E.buyShopItem(s, 0), ''); assert.strictEqual(s.inv.length, n + 1); assert(s.gold < 99999); });
t('продажа и массовая продажа хлама (не трогает заблокированное)', () => { const s = mk('warrior'); const a = E.addItem(s, E.genItem(E.rng(1), { il: 3, rarity: 0 })), b = E.addItem(s, E.genItem(E.rng(2), { il: 3, rarity: 0 })); b.lock = true; const g = E.sellJunk(s, 0); assert(g > 0 && s.inv.length === 1 && s.inv[0].lock); });
t('цены материалов/расходников: купить дороже продажи', () => { Object.keys(D.MATS).forEach((m) => assert(E.matBuy(m) > E.matSell(m))); Object.keys(D.CONS).forEach((c) => assert(E.consBuy(c) > E.consSell(c))); });
t('профессии: выбор необратим, нельзя две одинаковые, капы 20/10', () => { const s = E.newSlot({ name: 'Т', race: 'human', cls: 'warrior', portrait: 'human_m_1', uniq: 'phoenix' }); assert(E.setProfessions(s, 'smith', 'smith')); assert.strictEqual(E.setProfessions(s, 'smith', 'miner'), ''); assert(E.setProfessions(s, 'cook', 'fish')); assert.strictEqual(E.profCap(s.hero, 'smith'), 20); assert.strictEqual(E.profCap(s.hero, 'miner'), 10); assert.strictEqual(E.profCap(s.hero, 'cook'), 0); });
t('профессии: опыт повышает уровень до капа', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); E.profXp(s, 'smith', 1e6); assert.strictEqual(s.profs.smith.lv, 20); E.profXp(s, 'miner', 1e6); assert.strictEqual(s.profs.miner.lv, 10); });
t('крафт: нужны материалы и своя профессия; создаёт предмет с опытом', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); assert(E.craft(s, 'smelt_cu').err || E.craft(s, 'smith_smelt_cu').err); const rid = D.recipesFor('smith')[0].id; assert(E.craft(s, rid).err); const rec = D.recipesFor('smith')[0]; E.addMat(s, Object.keys(rec.mats)[0], 99); Object.keys(rec.mats).forEach((m) => E.addMat(s, m, 99)); s.gold = 999; const r = E.craft(s, rid); assert(!r.err, r.err); const alch = D.recipesFor('alch')[0].id; assert(E.craft(s, alch).err, 'чужая профессия'); });
t('крафт доступен по уровню рецепта', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); const hi = D.recipesFor('smith').find((r) => r.lv >= 10); assert(!E.recipeAvail(s, hi)); s.profs.smith.lv = hi.lv; assert(E.recipeAvail(s, hi)); });
t('добыча: нужен провиант и рабочая профессия', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); assert(E.gather(s, 'miner', 0).err); E.addMat(s, 'prov', 2); const r = E.gather(s, 'miner', 0); assert(!r.err && Object.keys(r.got).length > 0); assert.strictEqual(s.mats.prov, 1); assert(E.gather(s, 'herb', 0).err); });
t('зачарование требует профессию и материалы', () => { const s = mk('warrior', { prof1: 'smith', prof2: 'miner' }); const it = s.eq.weapon; assert.notStrictEqual(E.enchant(s, it.id, D.ENCHANTS[0].id), ''); const s2 = mk('mage', { prof1: 'ench', prof2: 'herb' }); const w = s2.eq.weapon; const en = D.ENCHANTS[0]; Object.keys(en.mats).forEach((m) => E.addMat(s2, m, 9)); s2.gold = 1e4; s2.profs.ench.lv = Math.max(1, en.lv); assert.strictEqual(E.enchant(s2, w.id, en.id), ''); assert.strictEqual(w.en, en.id); });
t('генерация вылазки: этажи, мини-босс, босс последним, события', () => D.DUNGEONS.forEach((d) => { const s = mk('warrior'); const run = E.genRun(s, d.id, 0, 123); const last = run.nodes[run.nodes.length - 1]; assert.strictEqual(last.t, 'boss'); assert(run.nodes.some((n) => n.t === 'mini')); assert(run.nodes.some((n) => n.t === 'ev')); assert.strictEqual(run.nodes.filter((n) => n.t === 'boss').length, 1); assert(new Set(run.nodes.map((n) => n.f)).size === d.floors); }));
t('открытие подземелий по цепочке; сложность по победам', () => { const s = mk('warrior'); assert(!E.dungeonUnlocked(s, 'mill')); s.story.flags.prologue_done = 1; assert(E.dungeonUnlocked(s, 'mill') && !E.dungeonUnlocked(s, 'wood')); s.prog.cleared.mill = 1; assert(E.dungeonUnlocked(s, 'wood')); assert(E.tierUnlocked(s, 'mill', 1) && !E.tierUnlocked(s, 'mill', 2)); });
t('вылазка: старт, зачёт при поражении вдвое меньше, лут идёт в сумку', () => { const s = mk('warrior'); s.story.flags.prologue_done = 1; assert.strictEqual(E.startRun(s, 'mill', 0), ''); assert(E.startRun(s, 'mill', 0)); s.run.bag.gold = 100; s.run.bag.items.push(E.genItem(E.rng(1), { il: 2, rarity: 1 }), E.genItem(E.rng(2), { il: 2, rarity: 1 })); const g0 = s.gold; const r = E.claimRun(s, 'lose'); assert.strictEqual(r.gold, 50); assert.strictEqual(s.gold, g0 + 50); assert.strictEqual(r.items.length, 1); assert.strictEqual(s.run, null); });
t('полная вылазка «Подвалы» автобоем: узлы, награды, уровень растёт', () => { const s = mk('warrior'); s.story.flags.prologue_done = 1; s.party = []; E.startRun(s, 'mill', 0); let guard = 60; while (s.run && guard--) { const node = s.run.nodes[s.run.node]; if (!node) break; if (node.t === 'ev') { C.resolveEvent(s, 'heal'); continue; } const B = C.startNodeBattle(s, { auto: true }); autoBattle(B); const rep = C.finishBattle(s, B); if (rep.result !== 'win') break; if (rep.bossDown) break; } assert(s.stats.kills > 0); assert(s.run.bag.xp > 0 || s.stats.deaths > 0); });
t('первый босс даёт искру Эха и открывает сложность', () => { const s = mk('warrior'); s.hero.level = 10; s.story.flags.prologue_done = 1; E.startRun(s, 'mill', 0); s.run.node = s.run.nodes.length - 1; s.party = []; const B = C.startNodeBattle(s, { auto: true }); B.foes.forEach((e) => { e.hp = 1; }); autoBattle(B); const rep = C.finishBattle(s, B); assert(rep.bossDown && rep.firstClear); assert.strictEqual(s.hero.bossPts, 1); assert.strictEqual(s.prog.cleared.mill, 1); });

console.log('Сюжет');
t('сцены: порядок D.STORY, все speaker-ключи и фоны известны', () => { D.STORY.forEach((st) => assert(D.SCENES[st.id], st.id)); const known = new Set(['bg', 'fx', 'title', 'set', 'give', 'cls', 'choice', 'if']); Object.values(D.SCENES).forEach((sc) => (function walk(ls) { ls.forEach((l) => { assert(Array.isArray(l)); if (!known.has(l[0])) assert(D.SPEAKERS[l[0]], 'speaker ' + l[0]); if (l[0] === 'choice') { assert(l[1].length >= 2); l[1].forEach((o) => { assert(o.t); if (o.r) walk(o.r); }); } if (l[0] === 'cls') Object.values(l[1]).forEach(walk); }); })(sc.lines)); });
t('портреты спикеров существуют (NPC)', () => Object.values(D.SPEAKERS).filter((s) => s.p).forEach((s) => assert(RPG.NPC_LOOK[s.p.replace('npc_', '')], s.p)));
t('объём сюжета ≥ 4000 слов', () => { const w = D.storyWords(); assert(w >= 4000, 'слов: ' + w); });
t('сюжет открывается по порядку; выборы ставят флаги; финиш сцены', () => { const s = mk('warrior'); assert.strictEqual(E.nextScene(s).id, 'prologue'); E.finishScene(s, 'prologue'); assert.strictEqual(E.nextScene(s).id, 'ch1_a'); E.finishScene(s, 'ch1_a'); assert(!E.sceneAvail(s, 'ch1_b')); s.prog.cleared.mill = 1; assert(E.sceneAvail(s, 'ch1_b')); E.setFlags(s, { vow: 'pity', trust: 1 }); E.setFlags(s, { trust: 2 }); assert.strictEqual(s.story.flags.vow, 'pity'); assert.strictEqual(s.story.flags.trust, 3); });
t('спутники приходят по сюжету и сами встают в отряд', () => { const s = mk('warrior'); assert.deepStrictEqual(E.unlockedComps(s), []); E.setFlags(s, { ch1_party: 1 }); E.finishScene(s, 'prologue'); assert.deepStrictEqual(s.party.sort(), ['kairen', 'tika']); E.setParty(s, ['irel']); assert.deepStrictEqual(s.party, []); });
t('подстановка имени героя в тексте', () => { const s = mk('warrior', { name: 'Рэйн' }); assert.strictEqual(E.fmtText('Привет, {name}!', s), 'Привет, Рэйн!'); });
t('выдача наград сюжета', () => { const s = mk('warrior'); const g = s.gold; E.give(s, { gold: 50, cons: { pot_hp1: 2 }, sp: 1, item: 'tear' }); assert.strictEqual(s.gold, g + 50); assert.strictEqual(s.hero.bossPts, 1); assert(s.inv.some((i) => i.nm === 'Слеза Осколка')); });
t('Кафедрал закрыт, пока не прочитана «Совет у горна»', () => { const s = mk('warrior'); s.story.flags.prologue_done = 1; s.prog.cleared.spire = 1; assert(!E.dungeonUnlocked(s, 'cathedral')); s.story.done.push('ch2_f'); assert(E.dungeonUnlocked(s, 'cathedral')); });

console.log('Сохранения');
const useStore = () => { S.store = mem(); return S.store; };
t('профиль: создание, сохранение, загрузка', () => { useStore(); const p = S.newProfile('Тест', '🦉'); p.slots[0] = mk('mage'); assert(S.save(p).ok); const r = S.load(p.id); assert(r.p && !r.recovered); assert.strictEqual(r.p.slots[0].hero.cls, 'mage'); assert.strictEqual(r.p.v, S.VERSION); assert.deepStrictEqual(S.listIds(), [p.id]); });
t('несколько слотов в профиле', () => { useStore(); const p = S.newProfile('Т', '🦉'); assert.strictEqual(p.slots.length, 3); p.slots[0] = mk('mage'); p.slots[2] = mk('rogue'); S.save(p); const q = S.load(p.id).p; assert(q.slots[0] && !q.slots[1] && q.slots[2]); });
t('резервный слот: порча основной записи → восстановление', () => { const st = useStore(); const p = S.newProfile('Т', '🦉'); p.slots[0] = mk('mage'); S.save(p); p.slots[0].gold = 123; S.save(p); st.setItem('arpg.p.' + p.id, '{битый json'); const r = S.load(p.id); assert(r.p && r.recovered); assert(S.hasBackup(p.id)); const rest = S.restoreBackup(p.id); assert(rest); assert(!S.load(p.id).recovered); });
t('миграция v1 → текущая', () => { const v1 = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/v1.json'), 'utf8')); assert.strictEqual(v1.v, 1); const p = S.migrate(v1); assert.strictEqual(p.v, S.VERSION); assert(S.validate(p)); const s = p.slots[0]; assert(Array.isArray(s.party) && s.tut && s.stats && s.buffs && s.hero.uspent && s.hero.bossPts === 0); assert.strictEqual(s.prog.cleared.mill, 1); assert.strictEqual(p.settings.music, true); assert.strictEqual(p.settings.sound, false); assert.strictEqual(s.gold, 777); assert.strictEqual(s.hero.name, 'Старичок'); E.derive(s); });
t('миграция v2 → текущая', () => { const v2 = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/v2.json'), 'utf8')); const p = S.migrate(v2); assert.strictEqual(p.v, S.VERSION); assert.strictEqual(p.slots[0].prog.cleared.mill, 1); assert.strictEqual(p.slots[0].hero.level, 7); });
t('мигрированный профиль загружается из хранилища', () => { const st = useStore(); const v1 = JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures/v1.json'), 'utf8')); st.setItem('arpg.p.' + v1.id, JSON.stringify(v1)); st.setItem('arpg.index', JSON.stringify([v1.id])); const sums = S.summaries(); assert.strictEqual(sums.length, 1); assert.strictEqual(sums[0].slots[0].name, 'Старичок'); });
t('сохранение из будущей версии не принимается', () => { const p = S.newProfile('Т', '🦉'); p.v = 99; assert.strictEqual(S.migrate(p), null); });
t('экспорт/импорт кодом: круг без потерь', () => { useStore(); const p = S.newProfile('Тест', '🦉'); p.slots[1] = mk('shield'); p.slots[1].gold = 4242; const code = S.exportCode(p); assert(/^ARPG3\./.test(code)); const r = S.importCode(code, { overwrite: true }); assert(!r.err); assert.strictEqual(r.p.slots[1].gold, 4242); assert.strictEqual(r.p.nick, 'Тест'); });
t('экспорт одного слота оставляет только его', () => { const p = S.newProfile('Т', '🦉'); p.slots[0] = mk('mage'); p.slots[1] = mk('rogue'); const r = S.importCode(S.exportCode(p, 1), { overwrite: true }); assert(!r.p.slots[0] && r.p.slots[1].hero.cls === 'rogue'); });
t('импорт: коллизия id → создаётся копия', () => { useStore(); const p = S.newProfile('Т', '🦉'); S.save(p); const r = S.importCode(S.exportCode(p)); assert.notStrictEqual(r.p.id, p.id); assert(/импорт/.test(r.p.nick)); });
t('импорт: повреждённые коды отклоняются', () => { const p = S.newProfile('Т', '🦉'); const code = S.exportCode(p); assert(S.importCode('мусор').err); assert(S.importCode(code.slice(0, -6)).err); assert(S.importCode(code.replace(/.$/, 'A') + 'A').err || true); const parts = code.split('.'); assert(S.importCode(parts[0] + '.' + parts[1] + '.' + (parts[2][5] === 'Q' ? 'R' : 'Q') + parts[2].slice(1, 5) + parts[2].slice(5)).err); assert(S.importCode('').err); });
t('квота хранилища: ошибка возвращается, не бросается', () => { S.store = { getItem: () => null, setItem: () => { const e = new Error('q'); e.name = 'QuotaExceededError'; throw e; }, removeItem() {} }; const r = S.save(S.newProfile('Т', '🦉')); assert(!r.ok && /места/.test(r.err)); });
t('удаление профиля чистит данные и копию', () => { const st = useStore(); const p = S.newProfile('Т', '🦉'); S.save(p); S.save(p); S.remove(p.id); assert.deepStrictEqual(S.listIds(), []); assert.strictEqual(st.getItem('arpg.p.' + p.id), null); assert.strictEqual(st.getItem('arpg.p.' + p.id + '.bak'), null); });
t('сериализация слота стабильна (JSON round-trip не меняет вычисления)', () => { const s = mk('rogue'); s.hero.level = 12; const a = E.derive(s), b = E.derive(JSON.parse(JSON.stringify(s))); assert.deepStrictEqual(a, b); });

console.log('PWA');
t('manifest.json: обязательные поля и иконки 192/512 + maskable', () => { const m = JSON.parse(fs.readFileSync(path.join(__dirname, '../manifest.json'), 'utf8')); assert(m.name && m.short_name && m.start_url && m.display === 'standalone' && m.orientation === 'portrait'); const has = (sz, pu) => m.icons.some((i) => i.sizes === sz && i.purpose === pu); assert(has('192x192', 'any') && has('512x512', 'any') && has('192x192', 'maskable') && has('512x512', 'maskable')); m.icons.forEach((i) => assert(fs.existsSync(path.join(__dirname, '..', i.src)), i.src)); });
t('sw.js: все файлы из прекеша существуют', () => { const sw = fs.readFileSync(path.join(__dirname, '../sw.js'), 'utf8'); const list = [...sw.matchAll(/'((?:js|css|icons)\/[^']+|index\.html|manifest\.json)'/g)].map((m) => m[1]); assert(list.length > 15); list.forEach((f) => assert(fs.existsSync(path.join(__dirname, '..', f)), f)); });
t('index.html подключает все скрипты, которые есть в js/', () => { const html = fs.readFileSync(path.join(__dirname, '../index.html'), 'utf8'); fs.readdirSync(path.join(__dirname, '../js')).forEach((f) => assert(html.includes('js/' + f), f)); });

console.log(`\nТесты: ${pass} ✓, ${fail} ✗`);
if (fail) { console.log(failed.join('\n')); process.exit(1); }
